# -*- coding: utf-8 -*-
tuple = (   ('{\\fontencoding{LELA}\\selectfont\\char202}', u'\u0140'),
    ('{\\fontencoding{LECO}\\selectfont\\char215}', u'\u0337'),
    ('{\\fontencoding{LECO}\\selectfont\\char225}', u'\u0361'),
    ('{\\fontencoding{LECO}\\selectfont\\char203}', u'\u032b'),
    ('{\\fontencoding{LECO}\\selectfont\\char218}', u'\u033a'),
    ('{\\fontencoding{LECO}\\selectfont\\char207}', u'\u032f'),
    ('{\\fontencoding{LECO}\\selectfont\\char185}', u'\u0319'),
    ('{\\fontencoding{LELA}\\selectfont\\char195}', u'\u01ba'),
    ('{\\fontencoding{LECO}\\selectfont\\char184}', u'\u0318'),
    ('{\\fontencoding{LECO}\\selectfont\\char216}', u'\u0338'),
    ('{\\fontencoding{LECO}\\selectfont\\char221}', u'\u033d'),
    ('{\\fontencoding{LECO}\\selectfont\\char220}', u'\u033c'),
    ('{\\fontencoding{LECO}\\selectfont\\char177}', u'\u0311'),
    ('{\\fontencoding{LECO}\\selectfont\\char219}', u'\u033b'),
    ('{\\fontencoding{LEIP}\\selectfont\\char202}', u'\u027f'),
    ('{\\fontencoding{LELA}\\selectfont\\char201}', u'\u013f'),
    ('{\\fontencoding{LELA}\\selectfont\\char91}', u'\u0138'),
    ('{\\fontencoding{LEIP}\\selectfont\\char61}', u'\u0258'),
    ('{\\fontencoding{LELA}\\selectfont\\char40}', u'\u0126'),
    ('{\\fontencoding{LELA}\\selectfont\\char47}', u'\u0166'),
    ('{\\fontencoding{LELA}\\selectfont\\char63}', u'\u0167'),
    ('{\\rlap{\\textbackslash}{{/}\\!\\!{/}}}', u'\u2afd-020E5'),
    ('\\cyrchar\\cyrhundredthousands ', u'\u0488'),
    ('\\mathbin{{:}\\!\\!{-}\\!\\!{:}}', u'\u223a'),
    ('\\NotNestedGreaterGreater ', u'\u2aa2-00338'),
    ('\\acute{\\ddot{\\upsilon}}', u'\u03b0'),
    ('\\cyrchar\\CYROMEGATITLO ', u'\u047c'),
    ('\\cyrchar\\cyromegatitlo ', u'\u047d'),
    ('\\mathsfbfsl{\\vartheta}', u'\ud7c5'),
    ('\\Pisymbol{ppi020}{117}', u'\u2a9d'),
    ('\\mathsfbfsl{\\vartheta}', u'\ud797'),
    ('\\cyrchar\\CYRSEMISFTSN ', u'\u048c'),
    ('\\cyrchar\\cyrsemisftsn ', u'\u048d'),
    ('\\cyrchar\\cyrthousands ', u'\u0482'),
    ('\\Pisymbol{ppi020}{105}', u'\u2a9e'),
    ('\\NestedGreaterGreater ', u'\u2aa2'),
    ('\\mathsfbfsl{\\vartheta}', u'\ud7a1'),
    ('\\not\\kern-0.3em\\times ', u'\u226d'),
    ('\\mathsfbfsl{\\vartheta}', u'\ud7b1'),
    ('\\mathsfbfsl{\\varkappa}', u'\ud7c6'),
    ('\\mathsfbfsl{\\varsigma}', u'\ud7bb'),
    ('\\ReverseUpEquilibrium ', u'\u296f'),
    ('\\textasteriskcentered', u'\u204e'),
    ('\\DownLeftRightVector ', u'\u2950'),
    ('\\leftrightsquigarrow ', u'\u21ad'),
    ('\\cyrchar\\CYROMEGARND ', u'\u047a'),
    ('\\cyrchar\\CYRpalochka ', u'\u04c0'),
    ('\\NotRightTriangleBar ', u'\u29d0-00338'),
    ('\\mathsfbfsl{\\Epsilon}', u'\ud794'),
    ('\\mathsfbfsl{\\Upsilon}', u'\ud7be'),
    ('\\cyrchar\\cyrmillions ', u'\u0489'),
    ('\\cyrchar\\CYRABHCHDSC ', u'\u04be'),
    ('\\cyrchar\\cyrabhchdsc ', u'\u04bf'),
    ('\\mathsfbfsl{\\Upsilon}', u'\ud7a4'),
    ('\\mathsfbfsl{\\Epsilon}', u'\ud7ae'),
    ('\\Pisymbol{ppi022}{87}', u'\u03d0'),
    ('\\cyrchar\\cyromegarnd ', u'\u047b'),
    ('\\textfractionsolidus', u'\u2044'),
    ('\\ElsevierGlyph{E20A}', u'\u2926'),
    ('\\ElsevierGlyph{E259}', u'\u2a3c'),
    ('\\ElsevierGlyph{300B}', u'\u300b'),
    ('\\cyrchar\\textnumero ', u'\u2116'),
    ('\\Longleftrightarrow ', u'\u27fa'),
    ('\\ElsevierGlyph{2242}', u'\u2242'),
    ('\\ElsevierGlyph{300A}', u'\u300a'),
    ('\\mathsfbf{\\varkappa}', u'\ud78c'),
    ('\\blacktriangleright ', u'\u25b8'),
    ('\\ElsevierGlyph{E395}', u'\u2a10'),
    ('\\mathsfbf{\\vartheta}', u'\ud767'),
    ('\\ElsevierGlyph{22C0}', u'\u22c0'),
    ('\\RightDownTeeVector ', u'\u295d'),
    ('\\ElsevierGlyph{E215}', u'\u297d'),
    ('\\ElsevierGlyph{22C1}', u'\u22c1'),
    ('\\ElsevierGlyph{E214}', u'\u297c'),
    ('\\ElsevierGlyph{E211}', u'\u2927'),
    ('\\ElsevierGlyph{E372}', u'\u29dc'),
    ('\\ElsevierGlyph{3018}', u'\u3018'),
    ('\\ElsevierGlyph{E25E}', u'\u2a34'),
    ('\\ElsevierGlyph{E61B}', u'\u29b6'),
    ('\\ElsevierGlyph{E838}', u'\u233d'),
    ('\\ElsevierGlyph{E20F}', u'\u2929'),
    ('\\ElsevierGlyph{E20E}', u'\u2928'),
    ('\\ElsevierGlyph{E25B}', u'\u2a2a'),
    ('\\ElsevierGlyph{225A}', u'\u225a'),
    ('\\longleftrightarrow ', u'\u27f7'),
    ('\\ElsevierGlyph{3019}', u'\u3019'),
    ('\\ElsevierGlyph{E21C}', u'\u2933'),
    ('\\ElsevierGlyph{E25E}', u'\u2a35'),
    ('\\ElsevierGlyph{E36E}', u'\u2a55'),
    ('\\ElsevierGlyph{E210}', u'\u292a'),
    ('\\ElsevierGlyph{E260}', u'\u29b5'),
    ('\\ElsevierGlyph{2238}', u'\u2238'),
    ('\\cyrchar\\CYRIOTBYUS ', u'\u046c'),
    ('\\RightDownVectorBar ', u'\u2955'),
    ('\\mathsfbfsl{\\Lambda}', u'\ud79a'),
    ('\\textperiodcentered ', u'\u02d9'),
    ('\\ElsevierGlyph{E21D}', u'\u2933-00338'),
    ('\\ElsevierGlyph{E291}', u'\u2994'),
    ('\\DownRightTeeVector ', u'\u295f'),
    ('\\cyrchar\\cyriotbyus ', u'\u046d'),
    ('\\ElsevierGlyph{E21A}', u'\u2936'),
    ('\\cyrchar\\CYRIOTLYUS ', u'\u0468'),
    ('\\NotLeftTriangleBar ', u'\u29cf-00338'),
    ('\\ElsevierGlyph{2232}', u'\u2232'),
    ('\\precedesnotsimilar ', u'\u22e8'),
    ('\\sim\\joinrel\\leadsto', u'\u27ff'),
    ('\\ElsevierGlyph{E25C}', u'\u2a2d'),
    ('\\textpertenthousand ', u'\u2031'),
    ('\\mathsfbf{\\varsigma}', u'\ud781'),
    ('\\cyrchar\\cyriotlyus ', u'\u0469'),
    ('\\mathsfbf{\\vartheta}', u'\ud78b'),
    ('\\ElsevierGlyph{E30D}', u'\u2aeb'),
    ('\\acute{\\ddot{\\iota}}', u'\u0390'),
    ('\\ElsevierGlyph{2129}', u'\u2129'),
    ('\\ElsevierGlyph{E219}', u'\u2937'),
    ('\\mathsfbfsl{\\varrho}', u'\ud7c8'),
    ('\\DownRightVectorBar ', u'\u2957'),
    ('\\ElsevierGlyph{E381}', u'\u25b1'),
    ('\\ElsevierGlyph{2274}', u'\u2274'),
    ('\\ElsevierGlyph{225F}', u'\u225f'),
    ('\\ensuremath{\\Elzpes}', u'\u20a7'),
    ('\\ElsevierGlyph{21B3}', u'\u21b3'),
    ('\\ElsevierGlyph{E20C}', u'\u2923'),
    ('\\ElsevierGlyph{E25A}', u'\u2a25'),
    ('\\mathsfbfsl{\\Lambda}', u'\ud7b4'),
    ('\\ElsevierGlyph{2275}', u'\u2275'),
    ('\\ElsevierGlyph{3018}', u'\u2985'),
    ('\\ElsevierGlyph{E212}', u'\u2905'),
    ('\\ElsevierGlyph{E20B}', u'\u2925'),
    ('\\ElsevierGlyph{2233}', u'\u2233'),
    ('\\ElsevierGlyph{225A}', u'\u2a63'),
    ('\\ElsevierGlyph{E20D}', u'\u2924'),
    ('\\ElsevierGlyph{E25D}', u'\u2a2e'),
    ('\\textperiodcentered', u'\xb7'),
    ('\\textpertenthousand', u'\u2031'),
    ('\\NotGreaterGreater ', u'\u226b-00338'),
    ('\\cyrchar\\CYRCHVCRS ', u'\u04b8'),
    ('\\cyrchar\\cyrchvcrs ', u'\u04b9'),
    ('\\leftrightharpoons ', u'\u21cb'),
    ('\\DownLeftVectorBar ', u'\u2956'),
    ('\\twoheadrightarrow ', u'\u21a0'),
    ('\\mathsfbfsl{\\Delta}', u'\ud793'),
    ('\\mathsfbfsl{\\Sigma}', u'\ud7bc'),
    ('\\mathsfbfsl{\\Omega}', u'\ud7a8'),
    ('\\rightleftharpoons ', u'\u21cc'),
    ('\\mathsfbfsl{\\Gamma}', u'\ud792'),
    ('\\cyrchar\\CYRCHLDSC ', u'\u04cb'),
    ('\\DownLeftTeeVector ', u'\u295e'),
    ('\\mathsfbfsl{\\Omega}', u'\ud7c2'),
    ('\\cyrchar\\CYRABHDZE ', u'\u04e0'),
    ('\\cyrchar\\cyrabhdze ', u'\u04e1'),
    ('\\mathbit{\\varkappa}', u'\ud752'),
    ('\\mathsfbfsl{\\Sigma}', u'\ud7a2'),
    ('\\cyrchar\\CYRCHRDSC ', u'\u04b6'),
    ('\\mathsfbf{\\Upsilon}', u'\ud784'),
    ('\\cyrchar\\cyrchrdsc ', u'\u04b7'),
    ('\\mathsfbfsl{\\Gamma}', u'\ud7ac'),
    ('\\blacktriangleleft ', u'\u25c2'),
    ('\\cyrchar\\cyrchldsc ', u'\u04cc'),
    ('\\mathsfbfsl{\\Delta}', u'\ud7ad'),
    ('\\NotNestedLessLess ', u'\u2aa1-00338'),
    ('\\mathsfbfsl{\\Kappa}', u'\ud7b3'),
    ('\\mathsfbf{\\Upsilon}', u'\ud76a'),
    ('\\blacktriangledown ', u'\u25be'),
    ('\\LeftDownTeeVector ', u'\u2961'),
    ('\\mathbit{\\vartheta}', u'\ud751'),
    ('\\mathsfbfsl{\\Kappa}', u'\ud799'),
    ('\\mathsfbf{\\Epsilon}', u'\ud774'),
    ('\\mathbit{\\varsigma}', u'\ud747'),
    ('\\mathsfbf{\\Epsilon}', u'\ud75a'),
    ('\\mathsfbfsl{\\varpi}', u'\ud7c9'),
    ('\\mathsfbfsl{\\Alpha}', u'\ud7aa'),
    ('\\downslopeellipsis ', u'\u22f1'),
    ('\\textquotedblright ', u'\u201d'),
    ('\\textasciidieresis ', u'\xa8'),
    ('\\LeftDownVectorBar ', u'\u2959'),
    ('\\mathsfbfsl{\\nabla}', u'\ud7a9'),
    ('\\textthreequarters ', u'\xbe'),
    ('\\mathsfbfsl{\\Alpha}', u'\ud790'),
    ('\\NotSquareSuperset ', u'\u2290-00338'),
    ('\\RightUpDownVector ', u'\u294f'),
    ('\\textasciidieresis', u'\xa8'),
    ('\\textthreesuperior', u'\xb3'),
    ('\\textthreequarters', u'\xbe'),
    ('\\textquotedblright', u'\u201d'),
    ('\\textreferencemark', u'\u203b'),
    ('\\textcolonmonetary', u'\u20a1'),
    ('\\rightharpoondown ', u'\u21c1'),
    ('\\textvisiblespace ', u'\u2423'),
    ('\\mathbit{\\Upsilon}', u'\ud74a'),
    ('\\downharpoonright ', u'\u21c2'),
    ('\\mathsfbfsl{\\Beta}', u'\ud7ab'),
    ('\\LeftUpDownVector ', u'\u2951'),
    ('\\cyrchar\\CYRSCHWA ', u'\u04d8'),
    ('\\cyrchar\\CYRUSHRT ', u'\u040e'),
    ('\\cyrchar\\cyrschwa ', u'\u04d9'),
    ('\\ntrianglerighteq ', u'\u22ed'),
    ('\\cyrchar\\CYRRTICK ', u'\u048e'),
    ('\\mathsfbfsl{\\Iota}', u'\ud798'),
    ('\\cyrchar\\CYRISHRT ', u'\u0419'),
    ('\\cyrchar\\cyrishrt ', u'\u0439'),
    ('\\RightTriangleBar ', u'\u29d0'),
    ('\\NotSucceedsTilde ', u'\u227f-00338'),
    ('\\cyrchar\\cyrrtick ', u'\u048f'),
    ('\\mathsfbfsl{\\Beta}', u'\ud791'),
    ('\\mathsfbf{\\Lambda}', u'\ud77a'),
    ('\\mathbf{\\vartheta}', u'\ud6b9'),
    ('\\RightUpTeeVector ', u'\u295c'),
    ('\\cyrchar\\CYROMEGA ', u'\u0460'),
    ('\\cyrchar\\CYRKOPPA ', u'\u0480'),
    ('\\cyrchar\\CYRKBEAK ', u'\u04a0'),
    ('\\cyrchar\\cyrkoppa ', u'\u0481'),
    ('\\cyrchar\\cyrkbeak ', u'\u04a1'),
    ('\\cyrchar\\CYRZHDSC ', u'\u0496'),
    ('\\cyrchar\\cyromega ', u'\u0461'),
    ('\\cyrchar\\cyrzhdsc ', u'\u0497'),
    ('\\cyrchar\\CYRSFTSN ', u'\u042c'),
    ('\\cyrchar\\cyrsftsn ', u'\u044c'),
    ('\\DownArrowUpArrow ', u'\u21f5'),
    ('\\mathsfbfsl{\\Zeta}', u'\ud7af'),
    ('\\hermitconjmatrix ', u'\u22b9'),
    ('\\mathsfbf{\\varrho}', u'\ud78e'),
    ('\\RightUpVectorBar ', u'\u2954'),
    ('\\mathsl{\\varsigma}', u'\ud70d'),
    ('\\textordmasculine ', u'\xba'),
    ('\\openbracketright ', u'\u301b'),
    ('\\cyrchar\\cyrghcrs ', u'\u0493'),
    ('\\mathsfbfsl{\\Zeta}', u'\ud795'),
    ('\\mathsfbfsl{\\Iota}', u'\ud7b2'),
    ('\\mathsl{\\varkappa}', u'\ud718'),
    ('\\cyrchar\\CYRABHHA ', u'\u04a8'),
    ('\\cyrchar\\cyrabhha ', u'\u04a9'),
    ('\\circlearrowright ', u'\u21bb'),
    ('\\cyrchar\\cyrushrt ', u'\u045e'),
    ('\\mathsl{\\vartheta}', u'\ud717'),
    ('\\cyrchar\\CYRKHCRS ', u'\u049e'),
    ('\\mathbit{\\Epsilon}', u'\ud73a'),
    ('\\textquotedblleft ', u'\u201c'),
    ('\\cyrchar\\cyrkhcrs ', u'\u049f'),
    ('\\mathbf{\\varsigma}', u'\ud6d3'),
    ('\\mathbit{\\Epsilon}', u'\ud720'),
    ('\\mathsl{\\vartheta}', u'\ud6f3'),
    ('\\cyrchar\\CYRTETSE ', u'\u04b4'),
    ('\\mathbf{\\varkappa}', u'\ud6de'),
    ('\\NotPrecedesTilde ', u'\u227e-00338'),
    ('\\cyrchar\\CYRHRDSN ', u'\u042a'),
    ('\\cyrchar\\cyrtetse ', u'\u04b5'),
    ('\\cyrchar\\cyrhrdsn ', u'\u044a'),
    ('\\mathbit{\\Upsilon}', u'\ud730'),
    ('\\twoheadleftarrow ', u'\u219e'),
    ('\\rightrightarrows ', u'\u21c9'),
    ('\\cyrchar\\CYRYHCRS ', u'\u04b0'),
    ('\\cyrchar\\cyryhcrs ', u'\u04b1'),
    ('\\mathbf{\\vartheta}', u'\ud6dd'),
    ('\\mathsfbf{\\Lambda}', u'\ud760'),
    ('\\vartriangleright ', u'\u22b3'),
    ('\\textquestiondown ', u'\xbf'),
    ('\\cyrchar\\CYRKVCRS ', u'\u049c'),
    ('\\cyrchar\\CYRABHCH ', u'\u04bc'),
    ('\\cyrchar\\cyrkvcrs ', u'\u049d'),
    ('\\cyrchar\\cyrabhch ', u'\u04bd'),
    ('\\cyrchar\\CYRGHCRS ', u'\u0492'),
    ('\\textordmasculine', u'\xba'),
    ('\\textquestiondown', u'\xbf'),
    ('\\textcompwordmark', u'\u200c'),
    ('\\textquotedblleft', u'\u201c'),
    ('\\textvisiblespace', u'\u2423'),
    ('\\mbox{\\texteuro} ', u'\u20ac'),
    ('\\cyrchar\\cyrndsc ', u'\u04a3'),
    ("\\cyrchar{\\'\\CYRG}", u'\u0403'),
    ('\\cyrchar\\CYRZDSC ', u'\u0498'),
    ('\\ntrianglelefteq ', u'\u22ec'),
    ('\\mathsfbf{\\Theta}', u'\ud777'),
    ('\\mathsfbf{\\Delta}', u'\ud759'),
    ('\\cyrchar\\cyrzdsc ', u'\u0499'),
    ('\\int\\!\\int\\!\\int ', u'\u222d'),
    ('\\mathsfbf{\\nabla}', u'\ud76f'),
    ('\\mathsfbf{\\Gamma}', u'\ud758'),
    ('\\mathsfbfsl{\\Phi}', u'\ud7a5'),
    ('\\cyrchar\\CYRIOTE ', u'\u0464'),
    ('\\mathsfbf{\\Omega}', u'\ud76e'),
    ('\\cyrchar\\CYRDZHE ', u'\u040f'),
    ('\\mathrm{\\ddot{Y}}', u'\u03ab'),
    ('\\curvearrowright ', u'\u21b7'),
    ('\\cyrchar\\CYRKDSC ', u'\u049a'),
    ('\\cyrchar\\CYRSHHA ', u'\u04ba'),
    ('\\cyrchar\\cyriote ', u'\u0465'),
    ('\\cyrchar\\cyrsdsc ', u'\u04ab'),
    ('\\cyrchar\\CYRTSHE ', u'\u040b'),
    ('\\rightthreetimes ', u'\u22cc'),
    ('\\mathbf{\\Epsilon}', u'\ud6ac'),
    ('\\nleftrightarrow ', u'\u21ae'),
    ('\\mathsfbfsl{\\Chi}', u'\ud7c0'),
    ('\\nLeftrightarrow ', u'\u21ce'),
    ('\\NotHumpDownHump ', u'\u224e-00338'),
    ('\\mathbit{\\Lambda}', u'\ud726'),
    ('&lt;\\kern-0.58em(', u'\u2993'),
    ('\\downharpoonleft ', u'\u21c3'),
    ('\\mathbit{\\varrho}', u'\ud754'),
    ('\\mathsfbfsl{\\Rho}', u'\ud7ba'),
    ('\\mathsfbf{\\Alpha}', u'\ud756'),
    ("\\cyrchar{\\'\\CYRK}", u'\u040c'),
    ('\\textasciimacron ', u'\xaf'),
    ('\\mathsfbfsl{\\Psi}', u'\ud7c1'),
    ('\\mathsfbf{\\varpi}', u'\ud78f'),
    ('\\mathsfbfsl{\\Tau}', u'\ud7bd'),
    ('\\mathsl{\\Upsilon}', u'\ud710'),
    ('\\cyrchar\\CYRTDSC ', u'\u04ac'),
    ('\\mathsl{\\Epsilon}', u'\ud700'),
    ('\\openbracketleft ', u'\u301a'),
    ('\\cyrchar\\cyrtdsc ', u'\u04ad'),
    ('\\perspcorrespond ', u'\u2a5e'),
    ('\\mathsfbfsl{\\Eta}', u'\ud796'),
    ('\\cyrchar\\CYRNDSC ', u'\u04a2'),
    ('\\cyrchar\\CYREREV ', u'\u042d'),
    ('\\rightleftarrows ', u'\u21c4'),
    ('\\mathbit{\\Lambda}', u'\ud740'),
    ('\\cyrchar\\cyrerev ', u'\u044d'),
    ('\\mathsfbfsl{\\Psi}', u'\ud7a7'),
    ('\\mathbf{\\Upsilon}', u'\ud6d6'),
    ('\\mathsl{\\Upsilon}', u'\ud6f6'),
    ('\\perspcorrespond ', u'\u2306'),
    ('\\textperthousand ', u'\u2030'),
    ('\\cyrchar\\cyrhdsc ', u'\u04b3'),
    ('\\circlearrowleft ', u'\u21ba'),
    ('\\mathbf{\\Upsilon}', u'\ud6bc'),
    ('\\leftrightarrows ', u'\u21c6'),
    ("\\cyrchar{\\'\\cyrg}", u'\u0453'),
    ('\\cyrchar\\CYROTLD ', u'\u04e8'),
    ('\\mathsfbfsl{\\Phi}', u'\ud7bf'),
    ('\\LeftUpTeeVector ', u'\u2960'),
    ('\\cyrchar\\cyrotld ', u'\u04e9'),
    ('\\cyrchar\\CYRSHCH ', u'\u0429'),
    ('\\greaterequivlnt ', u'\u2273'),
    ('\\vartriangleleft ', u'\u22b2'),
    ('\\cyrchar\\cyrshch ', u'\u0449'),
    ('\\mathsfbf{\\Omega}', u'\ud788'),
    ('\\mathsfbf{\\Kappa}', u'\ud75f'),
    ('\\leftharpoondown ', u'\u21bd'),
    ('\\rightsquigarrow ', u'\u21dd'),
    ('\\textquotesingle ', u"'"),
    ('\\mathsfbf{\\Gamma}', u'\ud772'),
    ('\\cyrchar\\cyrdzhe ', u'\u045f'),
    ('\\upslopeellipsis ', u'\u22f0'),
    ('\\mathsfbf{\\Sigma}', u'\ud782'),
    ('\\mathbf{\\Epsilon}', u'\ud6c6'),
    ('\\cyrchar\\CYRBYUS ', u'\u046a'),
    ('\\cyrchar\\CYRSDSC ', u'\u04aa'),
    ('\\mathsfbf{\\Delta}', u'\ud773'),
    ('\\cyrchar\\cyrkdsc ', u'\u049b'),
    ('\\cyrchar\\cyrshha ', u'\u04bb'),
    ('\\LeftRightVector ', u'\u294e'),
    ('\\mathrm{\\ddot{I}}', u'\u03aa'),
    ('\\mathsfbf{\\Sigma}', u'\ud768'),
    ('\\mathsfbf{\\Kappa}', u'\ud779'),
    ('\\cyrchar\\cyrtshe ', u'\u045b'),
    ('\\trianglerighteq ', u'\u22b5'),
    ('\\mathsfbfsl{\\phi}', u'\ud7c7'),
    ('\\LeftUpVectorBar ', u'\u2958'),
    ('\\cyrchar\\CYRLYUS ', u'\u0466'),
    ('\\mathsfbfsl{\\Rho}', u'\ud7a0'),
    ('\\mathsfbfsl{\\Tau}', u'\ud7a3'),
    ('\\bigtriangledown ', u'\u25bd'),
    ("\\cyrchar{\\'\\cyrk}", u'\u045c'),
    ('\\verymuchgreater ', u'\u22d9'),
    ('\\cyrchar\\cyrlyus ', u'\u0467'),
    ('\\mathsfbfsl{\\Chi}', u'\ud7a6'),
    ('\\LeftTriangleBar ', u'\u29cf'),
    ('\\mathsfbf{\\Theta}', u'\ud75d'),
    ('\\mathsfbf{\\Alpha}', u'\ud770'),
    ('\\cyrchar\\CYRFITA ', u'\u0472'),
    ('\\textordfeminine ', u'\xaa'),
    ('\\mathsfbfsl{\\Eta}', u'\ud7b0'),
    ('\\cyrchar\\CYRHDSC ', u'\u04b2'),
    ('\\NotSquareSubset ', u'\u228f-00338'),
    ('\\mathsl{\\Epsilon}', u'\ud6e6'),
    ('\\textordfeminine', u'\xaa'),
    ('\\textasciimacron', u'\xaf'),
    ('\\texttwosuperior', u'\xb2'),
    ('\\textonesuperior', u'\xb9'),
    ('\\textasciicircum', u'\u02c6'),
    ('\\textperthousand', u'\u2030'),
    ('\\textinterrobang', u'\u203d'),
    ('\\textservicemark', u'\u2120'),
    ('\\textmusicalnote', u'\u266a'),
    ('\\acute{\\epsilon}', u'\u03ad'),
    ('\\cyrchar\\CYRKHK ', u'\u04c3'),
    ('\\acute{\\upsilon}', u'\u03cd'),
    ('\\mathbit{\\Delta}', u'\ud739'),
    ('\\textasciigrave ', u'`'),
    ('\\mathsl{\\varrho}', u'\ud71a'),
    ('\\curvearrowleft ', u'\u21b6'),
    ('\\textexclamdown ', u'\xa1'),
    ('\\sphericalangle ', u'\u2222'),
    ('\\cyrchar\\CYRKSI ', u'\u046e'),
    ('\\rightharpoonup ', u'\u21c0'),
    ('\\cyrchar\\cyrlje ', u'\u0459'),
    ('\\RightTeeVector ', u'\u295b'),
    ('\\not\\sqsubseteq ', u'\u22e2'),
    ('\\mathbit{\\Gamma}', u'\ud738'),
    ('\\leftthreetimes ', u'\u22cb'),
    ('\\ntriangleright ', u'\u22eb'),
    ('\\textdoublepipe ', u'\u01c2'),
    ('\\cyrchar\\cyrkhk ', u'\u04c4'),
    ('\\mathsfbfsl{\\Pi}', u'\ud7b9'),
    ('\\cyrchar\\cyrksi ', u'\u046f'),
    ('\\cyrchar\\cyrnje ', u'\u045a'),
    ('\\cyrchar\\CYRDZE ', u'\u0405'),
    ('\\looparrowright ', u'\u21ac'),
    ('\\mathbit{\\Kappa}', u'\ud725'),
    ('\\mathsl{\\Lambda}', u'\ud706'),
    ('\\mathbit{\\nabla}', u'\ud735'),
    ('\\mathsfbfsl{\\Xi}', u'\ud79d'),
    ('\\cyrchar\\CYRERY ', u'\u042b'),
    ('\\cyrchar\\cyrery ', u'\u044b'),
    ('\\mathbf{\\Lambda}', u'\ud6cc'),
    ("\\mathrm{'\\Omega}", u'\u038f'),
    ('\\rightarrowtail ', u'\u21a3'),
    ('\\mathbit{\\Alpha}', u'\ud736'),
    ('\\textregistered ', u'\xae'),
    ('\\mathbit{\\Theta}', u'\ud723'),
    ('\\RightVectorBar ', u'\u2953'),
    ('\\mathsfbf{\\Beta}', u'\ud757'),
    ('\\mathbit{\\Omega}', u'\ud74e'),
    ('\\dblarrowupdown ', u'\u21c5'),
    ('\\not\\sqsupseteq ', u'\u22e3'),
    ('\\mathsfbfsl{\\Pi}', u'\ud79f'),
    ('\\notlessgreater ', u'\u2278'),
    ('\\textasciibreve ', u'\u02d8'),
    ('\\mathbf{\\varrho}', u'\ud6e0'),
    ('\\longrightarrow ', u'\u27f6'),
    ('\\cyrchar\\CYRDJE ', u'\u0402'),
    ('\\guilsinglright ', u'\u203a'),
    ('\\cyrchar\\CYRYAT ', u'\u0462'),
    ('\\mathsfbf{\\Iota}', u'\ud75e'),
    ('\\hookrightarrow ', u'\u21aa'),
    ('\\guillemotright ', u'\xbb'),
    ('\\textasciicaron ', u'\u02c7'),
    ('\\cyrchar\\cyrnhk ', u'\u04c8'),
    ('\\mathbit{\\varpi}', u'\ud755'),
    ('\\mathsfbf{\\Zeta}', u'\ud775'),
    ('\\hspace{0.166em}', u'\u2006'),
    ('\\mathbit{\\Delta}', u'\ud71f'),
    ('\\mathsfbfsl{\\Xi}', u'\ud7b7'),
    ('\\cyrchar\\CYRLJE ', u'\u0409'),
    ('\\mathsfbf{\\Zeta}', u'\ud75b'),
    ('\\arrowwaveright ', u'\u219d'),
    ('\\cyrchar\\CYRIZH ', u'\u0474'),
    ('\\cyrchar\\CYRGHK ', u'\u0494'),
    ('\\textonequarter ', u'\xbc'),
    ('\\cyrchar\\CYRNJE ', u'\u040a'),
    ('\\cyrchar\\cyrghk ', u'\u0495'),
    ('\\NestedLessLess ', u'\u2aa1'),
    ('\\leftleftarrows ', u'\u21c7'),
    ('\\approxnotequal ', u'\u2246'),
    ('\\mathbit{\\Theta}', u'\ud73d'),
    ('\\arrowwaveright ', u'\u219c'),
    ('\\cyrchar\\cyrdze ', u'\u0455'),
    ('\\mathbit{\\Sigma}', u'\ud748'),
    ('\\cyrchar\\CYRPSI ', u'\u0470'),
    ('\\mathbit{\\Omega}', u'\ud734'),
    ('\\cyrchar\\CYRGUP ', u'\u0490'),
    ('\\trianglelefteq ', u'\u22b4'),
    ('\\mathbit{\\Gamma}', u'\ud71e'),
    ('\\upharpoonright ', u'\u21be'),
    ('\\cyrchar\\cyrgup ', u'\u0491'),
    ('\\mathbit{\\Sigma}', u'\ud72e'),
    ('\\textasciitilde ', u'~'),
    ('\\hspace{0.167em}', u'\u2009'),
    ('\\mathsl{\\Lambda}', u'\ud6ec'),
    ('\\cyrchar\\CYRPHK ', u'\u04a6'),
    ('\\mathbf{\\Lambda}', u'\ud6b2'),
    ('\\cyrchar\\cyrpsi ', u'\u0471'),
    ('\\cyrchar\\cyrphk ', u'\u04a7'),
    ('\\cyrchar\\CYRNHK ', u'\u04c7'),
    ('\\mathbit{\\Alpha}', u'\ud71c'),
    ('\\textasciiacute ', u'\xb4'),
    ('\\downdownarrows ', u'\u21ca'),
    ('\\Longrightarrow ', u'\u27f9'),
    ('\\mathsfbf{\\Beta}', u'\ud771'),
    ('\\mathsfbf{\\Iota}', u'\ud778'),
    ('\\cyrchar\\cyrdje ', u'\u0452'),
    ('\\leftrightarrow ', u'\u2194'),
    ('\\mathbit{\\Kappa}', u'\ud73f'),
    ('\\notgreaterless ', u'\u2279'),
    ('\\Leftrightarrow ', u'\u21d4'),
    ('\\textexclamdown', u'\xa1'),
    ('\\textregistered', u'\xae'),
    ('\\textasciiacute', u'\xb4'),
    ('\\guillemotright', u'\xbb'),
    ('\\textonequarter', u'\xbc'),
    ('\\textasciicaron', u'\u02c7'),
    ('\\textasciitilde', u'\u02dc'),
    ('\\textasciibreve', u'\u02d8'),
    ('\\textquoteright', u'\u2019'),
    ('\\quotesinglbase', u'\u201a'),
    ('\\guilsinglright', u'\u203a'),
    ('\\textrightarrow', u'\u2192'),
    ('\\textopenbullet', u'\u25e6'),
    ('\\guillemotleft ', u'\xab'),
    ('\\mathbf{\\Theta}', u'\ud6af'),
    ('\\triangleright ', u'\u25b9'),
    ('\\cyrchar\\cyrje ', u'\u0458'),
    ('\\cyrchar\\CYRUK ', u'\u0478'),
    ('\\mathsl{\\Kappa}', u'\ud705'),
    ('\\mathbf{\\Gamma}', u'\ud6c4'),
    ('\\textfrac{5}{8}', u'\u215d'),
    ('\\looparrowleft ', u'\u21ab'),
    ('\\cyrchar\\CYRYU ', u'\u042e'),
    ('\\mathbf{\\Delta}', u'\ud6c5'),
    ('\\cyrchar\\cyryu ', u'\u044e'),
    ('\\mathsl{\\Delta}', u'\ud6e5'),
    ('\\textdaggerdbl ', u'\u2021'),
    ('\\divideontimes ', u'\u22c7'),
    ('\\textparagraph ', u'\xb6'),
    ('\\mathbf{\\Sigma}', u'\ud6ba'),
    ('\\cyrchar\\cyruk ', u'\u0479'),
    ('\\mathsl{\\Omega}', u'\ud6fa'),
    ('\\mathsfbf{\\Phi}', u'\ud785'),
    ('\\cyrchar\\CYRIE ', u'\u0404'),
    ('\\textfrac{2}{5}', u'\u2156'),
    ('\\textfrac{3}{8}', u'\u215c'),
    ('\\LeftVectorBar ', u'\u2952'),
    ('\\leftarrowtail ', u'\u21a2'),
    ('\\cyrchar\\CYRNG ', u'\u04a4'),
    ('\\cyrchar\\CYRYA ', u'\u042f'),
    ('\\cyrchar\\cyrya ', u'\u044f'),
    ('\\mathsl{\\Theta}', u'\ud703'),
    ('\\cyrchar\\cyrng ', u'\u04a5'),
    ('\\ddot{\\upsilon}', u'\u03cb'),
    ('\\measuredangle ', u'\u2221'),
    ('\\Longleftarrow ', u'\u27f8'),
    ('\\mathsl{\\Gamma}', u'\ud6fe'),
    ('\\mathsfbf{\\Psi}', u'\ud76d'),
    ('\\mathsfbf{\\phi}', u'\ud78d'),
    ('\\cyrchar\\CYRZH ', u'\u0416'),
    ('\\cyrchar\\cyrzh ', u'\u0436'),
    ('\\mathsfbf{\\Tau}', u'\ud783'),
    ('\\cyrchar\\cyrii ', u'\u0456'),
    ('\\mathsl{\\Gamma}', u'\ud6e4'),
    ('\\cyrchar\\CYRYO ', u'\u0401'),
    ('\\guilsinglleft ', u'\u2039'),
    ('\\mathbf{\\Alpha}', u'\ud6c2'),
    ('\\mathsfbf{\\Eta}', u'\ud75c'),
    ('\\mathsl{\\Alpha}', u'\ud6e2'),
    ('\\hspace{0.33em}', u'\u2004'),
    ('\\mathbit{\\Zeta}', u'\ud73b'),
    ('\\textfrac{5}{6}', u'\u215a'),
    ('\\mathbf{\\Delta}', u'\ud6ab'),
    ('\\mathbf{\\Kappa}', u'\ud6cb'),
    ('\\mathsl{\\Kappa}', u'\ud6eb'),
    ('\\mathsfbf{\\Rho}', u'\ud766'),
    ('\\mathsl{\\Omega}', u'\ud714'),
    ('\\mathbf{\\Omega}', u'\ud6c0'),
    ('\\cyrchar\\cyryi ', u'\u0457'),
    ('\\mathbit{\\Iota}', u'\ud724'),
    ('\\mathsfbf{\\Eta}', u'\ud776'),
    ('\\mathsfbf{\\Chi}', u'\ud786'),
    ('\\mathbit{\\Beta}', u'\ud71d'),
    ('\\mathbf{\\nabla}', u'\ud6c1'),
    ('\\mathbf{\\varpi}', u'\ud6e1'),
    ('\\hspace{0.25em}', u'\u2005'),
    ('\\mathsl{\\varpi}', u'\ud71b'),
    ('\\mathbit{\\Zeta}', u'\ud721'),
    ('\\mathsfbf{\\Phi}', u'\ud76b'),
    ('\\fallingdotseq ', u'\u2252'),
    ('\\mathbit{\\Beta}', u'\ud737'),
    ('\\cyrchar\\CYRJE ', u'\u0408'),
    ('\\cyrchar\\CYRSH ', u'\u0428'),
    ('\\cyrchar\\cyrsh ', u'\u0448'),
    ('\\longleftarrow ', u'\u27f5'),
    ('\\mathsl{\\Delta}', u'\ud6ff'),
    ('\\textfrac{1}{3}', u'\u2153'),
    ('\\mathbf{\\Sigma}', u'\ud6d4'),
    ('\\mathsl{\\Sigma}', u'\ud6f4'),
    ('\\textfrac{1}{5}', u'\u2155'),
    ('\\bigtriangleup ', u'\u25b3'),
    ('\\NotEqualTilde ', u'\u2242-00338'),
    ('\\cyrchar\\CYROT ', u'\u047e'),
    ('\\textfrac{4}{5}', u'\u2158'),
    ('\\textbrokenbar ', u'\xa6'),
    ('\\mathbf{\\Gamma}', u'\ud6aa'),
    ('\\textfrac{1}{8}', u'\u215b'),
    ('\\textfrac{7}{8}', u'\u215e'),
    ('\\cyrchar\\cyrie ', u'\u0454'),
    ('\\textbackslash ', u'\\'),
    ('\\mathbf{\\Alpha}', u'\ud6a8'),
    ('\\cyrchar\\CYRAE ', u'\u04d4'),
    ('\\mathsfbf{\\Tau}', u'\ud769'),
    ('\\cyrchar\\cyrot ', u'\u047f'),
    ('\\textfrac{3}{5}', u'\u2157'),
    ('\\mathbf{\\Omega}', u'\ud6da'),
    ('\\mathbf{\\theta}', u'\ud6c9'),
    ('\\cyrchar\\cyrae ', u'\u04d5'),
    ('\\mathsl{\\Theta}', u'\ud6e9'),
    ('\\mathsfbf{\\Chi}', u'\ud76c'),
    ('\\blacktriangle ', u'\u25b4'),
    ('\\leftharpoonup ', u'\u21bc'),
    ('\\textfrac{2}{3}', u'\u2154'),
    ('\\hookleftarrow ', u'\u21a9'),
    ('\\mathsl{\\Sigma}', u'\ud70e'),
    ('\\UpEquilibrium ', u'\u296e'),
    ('\\texttrademark ', u'\u2122'),
    ('\\mathsl{\\Alpha}', u'\ud6fc'),
    ('\\cyrchar\\CYRII ', u'\u0406'),
    ('\\textfrac{1}{6}', u'\u2159'),
    ('\\textcopyright ', u'\xa9'),
    ('\\varsubsetneqq ', u'\u228a-0FE00'),
    ('\\mathbit{\\Iota}', u'\ud73e'),
    ('\\cyrchar\\cyryo ', u'\u0451'),
    ('\\mathsfbf{\\Rho}', u'\ud780'),
    ('\\ntriangleleft ', u'\u22ea'),
    ('\\mathsfbf{\\Psi}', u'\ud787'),
    ('\\LeftTeeVector ', u'\u295a'),
    ('\\mathsl{\\nabla}', u'\ud6fb'),
    ('\\cyrchar\\CYRYI ', u'\u0407'),
    ('\\cyrchar\\CYRCH ', u'\u0427'),
    ('\\cyrchar\\cyrch ', u'\u0447'),
    ('\\mathbf{\\Kappa}', u'\ud6b1'),
    ('\\upharpoonleft ', u'\u21bf'),
    ('\\stackrel{*}{=}', u'\u2a6e'),
    ('\\rule{1em}{1pt}', u'\u2015'),
    ('\\rightanglearc ', u'\u22be'),
    ('\\textbrokenbar', u'\xa6'),
    ('\\textcopyright', u'\xa9'),
    ('\\guillemotleft', u'\xab'),
    ('\\textparagraph', u'\xb6'),
    ('\\textquoteleft', u'\u2018'),
    ('\\textdaggerdbl', u'\u2021'),
    ('\\guilsinglleft', u'\u2039'),
    ('\\texttrademark', u'\u2122'),
    ('\\textestimated', u'\u212e'),
    ('\\textleftarrow', u'\u2190'),
    ('\\textdownarrow', u'\u2193'),
    ('\\textbigcircle', u'\u25ef'),
    ('\\textcopyright', u'\xa9'),
    ('\\textparagraph', u'\xb6'),
    ('\\textdaggerdbl', u'\u2021'),
    ('\\cyrchar\\CYRI ', u'\u0418'),
    ('\\cyrchar\\cyri ', u'\u0438'),
    ('\\mathsfbfsl{m}', u'\ud662'),
    ('\\mathsfbfsl{o}', u'\ud664'),
    ('\\cyrchar\\CYRU ', u'\u0423'),
    ('\\mathbit{\\Tau}', u'\ud749'),
    ('\\cyrchar\\cyru ', u'\u0443'),
    ('\\triangleleft ', u'\u25c3'),
    ('\\mathsfbfsl{n}', u'\ud663'),
    ('\\mathsfbfsl{e}', u'\ud65a'),
    ('\\RoundImplies ', u'\u2970'),
    ('\\mathsfbfsl{I}', u'\ud644'),
    ('\\cyrchar\\CYRY ', u'\u04ae'),
    ('\\mathsfbf{\\Pi}', u'\ud765'),
    ('\\mathchar"2208', u'\u2316'),
    ('\\cyrchar\\CYRF ', u'\u0424'),
    ('\\cyrchar\\cyry ', u'\u04af'),
    ('\\mathbf{\\Beta}', u'\ud6c3'),
    ('\\cyrchar\\cyrf ', u'\u0444'),
    ('\\mathsfbfsl{K}', u'\ud646'),
    ('\\mathsfbfsl{c}', u'\ud658'),
    ('\\mathsfbfsl{S}', u'\ud64e'),
    ('\\mathsfbfsl{q}', u'\ud666'),
    ('\\NotHumpEqual ', u'\u224f-00338'),
    ('\\mathsfbfsl{R}', u'\ud64d'),
    ('\\hspace{0.6em}', u'\u2002'),
    ('\\cyrchar\\CYRK ', u'\u041a'),
    ('\\cyrchar\\cyrk ', u'\u043a'),
    ('\\mathsfbfsl{H}', u'\ud643'),
    ('\\varsupsetneq ', u'\u228b-0FE00'),
    ('\\mathsfbfsl{x}', u'\ud66d'),
    ('\\cyrchar\\CYRH ', u'\u0425'),
    ('\\cyrchar\\cyrh ', u'\u0445'),
    ('\\mathsfbfsl{d}', u'\ud659'),
    ('\\cyrchar\\CYRR ', u'\u0420'),
    ('\\textsterling ', u'\xa3'),
    ('\\cyrchar\\cyrr ', u'\u0440'),
    ('\\mathsfbfsl{w}', u'\ud66c'),
    ('\\mathsfbfsl{D}', u'\ud63f'),
    ('\\surfintegral ', u'\u222f'),
    ('\\mathsfbfsl{T}', u'\ud64f'),
    ('\\mathsfbfsl{b}', u'\ud657'),
    ('\\mathbit{\\Eta}', u'\ud73c'),
    ('\\mathbf{\\Zeta}', u'\ud6ad'),
    ('\\DownArrowBar ', u'\u2913'),
    ('\\mathsfbfsl{z}', u'\ud66f'),
    ('\\cyrchar\\CYRS ', u'\u0421'),
    ('\\mathbit{\\Rho}', u'\ud746'),
    ('\\blacklozenge ', u'\u29eb'),
    ('\\cyrchar\\cyrs ', u'\u0441'),
    ('\\mathsfbfsl{U}', u'\ud650'),
    ('\\mathbit{\\Phi}', u'\ud74b'),
    ('\\mathsl{\\Iota}', u'\ud704'),
    ('\\mathsfbf{\\Pi}', u'\ud77f'),
    ('\\mathsfbfsl{k}', u'\ud660'),
    ('\\cyrchar\\CYRZ ', u'\u0417'),
    ('\\mathsfbfsl{y}', u'\ud66e'),
    ('\\textcurrency ', u'\xa4'),
    ('\\mathsfbfsl{N}', u'\ud649'),
    ('\\cyrchar\\cyrz ', u'\u0437'),
    ('\\mathbit{\\Psi}', u'\ud733'),
    ('\\acute{\\omega}', u'\u03ce'),
    ('\\mathsfbfsl{v}', u'\ud66b'),
    ('\\cyrchar\\CYRT ', u'\u0422'),
    ('\\not\\subseteq ', u'\u2288'),
    ('\\cyrchar\\cyrt ', u'\u0442'),
    ('\\mathsfbfsl{a}', u'\ud656'),
    ('\\mathsfbfsl{t}', u'\ud669'),
    ('\\mathsfbfsl{l}', u'\ud661'),
    ('\\mathbit{\\Phi}', u'\ud731'),
    ('\\mathsfbfsl{Y}', u'\ud654'),
    ('\\mathsfbfsl{X}', u'\ud653'),
    ('\\mathsfbfsl{u}', u'\ud66a'),
    ('\\cyrchar\\CYRG ', u'\u0413'),
    ('\\cyrchar\\cyrg ', u'\u0433'),
    ('\\mathbit{\\Psi}', u'\ud74d'),
    ('\\mathsfbfsl{P}', u'\ud64b'),
    ('\\texttildelow ', u'\u02dc'),
    ('\\mathsfbfsl{j}', u'\ud65f'),
    ('\\verymuchless ', u'\u22d8'),
    ('\\cyrchar\\CYRO ', u'\u041e'),
    ('\\cyrchar\\cyro ', u'\u043e'),
    ('\\mathsfbfsl{E}', u'\ud640'),
    ('\\mathsfbfsl{A}', u'\ud63c'),
    ('\\mathsfbfsl{G}', u'\ud642'),
    ('\\lessequivlnt ', u'\u2272'),
    ('\\mathsfbfsl{Q}', u'\ud64c'),
    ('\\mathsfbfsl{Z}', u'\ud655'),
    ('\\mathsl{\\Iota}', u'\ud6ea'),
    ('\\cyrchar\\CYRD ', u'\u0414'),
    ('\\mathsfbfsl{g}', u'\ud65c'),
    ('\\cyrchar\\cyrd ', u'\u0434'),
    ('\\textvartheta ', u'\u03d1'),
    ('\\mathsl{\\Zeta}', u'\ud701'),
    ('\\mathsfbfsl{J}', u'\ud645'),
    ('\\mathsfbfsl{O}', u'\ud64a'),
    ('\\cyrchar\\CYRP ', u'\u041f'),
    ('\\cyrchar\\cyrp ', u'\u043f'),
    ('\\mathbf{\\Iota}', u'\ud6ca'),
    ('\\mathbf{\\Beta}', u'\ud6a9'),
    ('\\mathsfbfsl{W}', u'\ud652'),
    ('\\triangledown ', u'\u25bf'),
    ('\\mathsfbfsl{i}', u'\ud65e'),
    ('\\cyrchar\\CYRE ', u'\u0415'),
    ('\\cyrchar\\cyre ', u'\u0435'),
    ('\\mathbit{\\phi}', u'\ud753'),
    ('\\mathsfbfsl{p}', u'\ud665'),
    ('\\cyrchar\\CYRA ', u'\u0410'),
    ('\\cyrchar\\cyra ', u'\u0430'),
    ('\\mathbf{\\Zeta}', u'\ud6c7'),
    ('\\mathsl{\\Zeta}', u'\ud6e7'),
    ('\\cyrchar\\CYRL ', u'\u041b'),
    ('\\mathsfbfsl{L}', u'\ud647'),
    ('\\cyrchar\\cyrl ', u'\u043b'),
    ('\\mathsfbf{\\Xi}', u'\ud763'),
    ('\\mathbit{\\Chi}', u'\ud732'),
    ('\\mathsfbfsl{r}', u'\ud667'),
    ('\\cyrchar\\CYRC ', u'\u0426'),
    ('\\mathbit{\\Eta}', u'\ud722'),
    ('\\cyrchar\\cyrc ', u'\u0446'),
    ('\\mathsl{\\Beta}', u'\ud6fd'),
    ('\\cyrchar\\CYRB ', u'\u0411'),
    ('\\cyrchar\\cyrb ', u'\u0431'),
    ('\\mathsfbfsl{M}', u'\ud648'),
    ('\\mathsfbfsl{B}', u'\ud63d'),
    ('\\mathsfbfsl{h}', u'\ud65d'),
    ('\\mathsfbf{\\Xi}', u'\ud77d'),
    ('\\mathbit{\\Tau}', u'\ud72f'),
    ('\\mathbit{\\Chi}', u'\ud74c'),
    ('\\cyrchar\\CYRM ', u'\u041c'),
    ('\\cyrchar\\cyrm ', u'\u043c'),
    ('\\mathsl{\\Beta}', u'\ud6e3'),
    ('\\mathsfbfsl{s}', u'\ud668'),
    ('\\mathsfbfsl{F}', u'\ud641'),
    ('\\risingdotseq ', u'\u2253'),
    ('\\mathsfbfsl{f}', u'\ud65b'),
    ('\\mathsfbfsl{V}', u'\ud651'),
    ('\\not\\supseteq ', u'\u2289'),
    ('\\mathbit{\\Rho}', u'\ud72c'),
    ('\\cyrchar\\CYRV ', u'\u0412'),
    ('\\cyrchar\\cyrv ', u'\u0432'),
    ('\\cyrchar\\CYRN ', u'\u041d'),
    ('\\mathbf{\\Iota}', u'\ud6b0'),
    ('\\cyrchar\\cyrn ', u'\u043d'),
    ('\\mathsfbfsl{C}', u'\ud63e'),
    ('\\textsterling', u'\xa3'),
    ('\\textcurrency', u'\xa4'),
    ('\\textacutedbl', u'\u02dd'),
    ('\\CYRSEMISFTSN', u'\u048c'),
    ('\\cyrsemisftsn', u'\u048d'),
    ('\\quotedblbase', u'\u201e'),
    ('\\textellipsis', u'\u2026'),
    ('\\textdiscount', u'\u2052'),
    ('\\textcircledP', u'\u2117'),
    ('\\textsterling', u'\xa3'),
    ('\\textellipsis', u'\u2026'),
    ('\\mathsl{\\Phi}', u'\ud711'),
    ('\\nolinebreak ', u'\u2060'),
    ('\\mathbf{\\Chi}', u'\ud6d8'),
    ('\\mathbf{\\Rho}', u'\ud6b8'),
    ('\\preccurlyeq ', u'\u227c'),
    ('\\mathbf{\\Rho}', u'\ud6d2'),
    ('\\backepsilon ', u'\u03f6'),
    ('\\mathsl{\\Chi}', u'\ud6f8'),
    ('\\mathbf{\\Eta}', u'\ud6ae'),
    ('\\mathbf{\\Psi}', u'\ud6d9'),
    ('\\mathbf{\\Phi}', u'\ud6d7'),
    ('\\mathsl{\\Phi}', u'\ud6f7'),
    ('\\updownarrow ', u'\u2195'),
    ('\\mathbit{\\Pi}', u'\ud745'),
    ('\\mathsl{\\Psi}', u'\ud6f9'),
    ('\\eqslantless ', u'\u2a95'),
    ('\\acute{\\iota}', u'\u03af'),
    ('\\mathsl{\\Psi}', u'\ud713'),
    ('\\mathbit{\\Pi}', u'\ud72b'),
    ('\\circledcirc ', u'\u229a'),
    ('\\NotLessLess ', u'\u226a-00338'),
    ('\\nRightarrow ', u'\u21cf'),
    ('\\succnapprox ', u'\u2aba'),
    ('\\RuleDelayed ', u'\u29f4'),
    ('\\mathsl{\\Eta}', u'\ud702'),
    ('\\mathbf{\\Psi}', u'\ud6bf'),
    ('\\mathbf{\\phi}', u'\ud6df'),
    ('\\nrightarrow ', u'\u219b'),
    ('\\circleddash ', u'\u229d'),
    ('\\mathbf{\\Tau}', u'\ud6d5'),
    ('\\mathsl{\\Tau}', u'\ud70f'),
    ('\\Rrightarrow ', u'\u21db'),
    ('\\mathsl{\\Tau}', u'\ud6f5'),
    ('\\textsection ', u'\xa7'),
    ('\\volintegral ', u'\u2230'),
    ('\\vartriangle ', u'\u25b5'),
    ('\\mathsl{\\Chi}', u'\ud712'),
    ('\\blacksquare ', u'\u25aa'),
    ('\\mathbf{\\Eta}', u'\ud6c8'),
    ('\\mathsl{\\Eta}', u'\ud6e8'),
    ('\\textonehalf ', u'\xbd'),
    ('\\clwintegral ', u'\u2231'),
    ('\\mathbf{\\Chi}', u'\ud6be'),
    ('\\quarternote ', u'\u2669'),
    ('\\succcurlyeq ', u'\u227d'),
    ('\\curlyeqsucc ', u'\u22df'),
    ('\\mathbf{\\Phi}', u'\ud6bd'),
    ('\\mathsl{\\Rho}', u'\ud6f2'),
    ('\\mathbf{\\Tau}', u'\ud6bb'),
    ('\\mathsl{\\Rho}', u'\ud70c'),
    ('\\sagittarius ', u'\u2650'),
    ('\\Updownarrow ', u'\u21d5'),
    ('\\mathsl{\\phi}', u'\ud719'),
    ('\\mathbit{\\Xi}', u'\ud743'),
    ('\\forcesextra ', u'\u22a8'),
    ('\\precnapprox ', u'\u2ab9'),
    ('\\capricornus ', u'\u2651'),
    ('\\curlyeqprec ', u'\u22de'),
    ('\\mathbit{\\Xi}', u'\ud729'),
    ('\\textsection', u'\xa7'),
    ('\\textonehalf', u'\xbd'),
    ('\\CYRABHCHDSC', u'\u04be'),
    ('\\cyrabhchdsc', u'\u04bf'),
    ('\\CYRpalochka', u'\u04c0'),
    ('\\CYRGDSCHCRS', u'\u04fa'),
    ('\\cyrgdschcrs', u'\u04fb'),
    ('\\textcelsius', u'\u2103'),
    ('\\textuparrow', u'\u2191'),
    ('\\textsection', u'\xa7'),
    ('\\mathsfbf{w}', u'\ud604'),
    ('\\mathfrak{C}', u'\u212d'),
    ('\\mathslbb{t}', u'\ud599'),
    ('\\mathbf{\\Xi}', u'\ud6cf'),
    ('\\mathfrak{S}', u'\ud516'),
    ('\\mathsl{\\Xi}', u'\ud6ef'),
    ('\\mathsfbf{l}', u'\ud5f9'),
    ('\\mathsfsl{H}', u'\ud60f'),
    ('\\mathslbb{i}', u'\ud58e'),
    ('\\mathsfsl{n}', u'\ud62f'),
    ('\\textdagger ', u'\u2020'),
    ('\\mathsfsl{c}', u'\ud624'),
    ('\\mathsfbf{a}', u'\ud5ee'),
    ('\\mathslbb{N}', u'\ud579'),
    ('\\mathslbb{X}', u'\ud583'),
    ('\\mathfrak{U}', u'\ud518'),
    ('\\mathfrak{q}', u'\ud52e'),
    ('\\mathsfsl{y}', u'\ud63a'),
    ('\\mathsfbf{m}', u'\ud5fa'),
    ('\\mathsfbf{P}', u'\ud5e3'),
    ('\\mathsfbf{3}', u'\ud7ef'),
    ('\\mathslbb{M}', u'\ud578'),
    ('{{/}\\!\\!{/}}', u'\u2afd'),
    ('\\mathslbb{s}', u'\ud598'),
    ('\\mathsfsl{d}', u'\ud625'),
    ("\\'{$\\alpha$}", u'\u03ac'),
    ('\\not\\succeq ', u'\u2ab0-00338'),
    ('\\mathsfbf{k}', u'\ud5f8'),
    ('\\mathslbb{Z}', u'\ud585'),
    ('\\UpArrowBar ', u'\u2912'),
    ('\\mathfrak{W}', u'\ud51a'),
    ('\\mathfrak{A}', u'\ud504'),
    ('\\mathsfsl{w}', u'\ud638'),
    ('\\nLeftarrow ', u'\u21cd'),
    ('\\mathfrak{H}', u'\u210c'),
    ('\\mathsfbf{R}', u'\ud5e5'),
    ('\\mathfrak{M}', u'\ud510'),
    ('\\mathslbb{O}', u'\ud57a'),
    ('\\mathfrak{Q}', u'\ud514'),
    ('\\mathsfbf{v}', u'\ud603'),
    ('\\mathfrak{B}', u'\ud505'),
    ('\\mathsfsl{b}', u'\ud623'),
    ('\\mathfrak{h}', u'\ud525'),
    ('\\mathfrak{R}', u'\u211c'),
    ('\\mathsfbf{G}', u'\ud5da'),
    ('\\mathfrak{g}', u'\ud524'),
    ('\\mathslbb{S}', u'\ud57e'),
    ('\\mathslbb{j}', u'\ud58f'),
    ('\\textbullet ', u'\u2022'),
    ('\\succapprox ', u'\u227f'),
    ('\\mathsfsl{m}', u'\ud62e'),
    ('\\mathfrak{I}', u'\u2111'),
    ('\\complement ', u'\u2201'),
    ('\\mathslbb{Y}', u'\ud584'),
    ('\\mathfrak{L}', u'\ud50f'),
    ('\\mathfrak{V}', u'\ud519'),
    ('\\mathsfsl{R}', u'\ud619'),
    ('\\mathsfbf{2}', u'\ud7ee'),
    ('\\mathfrak{r}', u'\ud52f'),
    ('\\mathsfsl{x}', u'\ud639'),
    ('\\mathsfbf{Q}', u'\ud5e4'),
    ('\\nsubseteqq ', u'\u2ac5-00338'),
    ('\\mathslbb{D}', u'\ud56f'),
    ('\\mathslbb{V}', u'\ud581'),
    ('\\mathbf{\\Pi}', u'\ud6b7'),
    ('\\mathfrak{y}', u'\ud536'),
    ('\\curlywedge ', u'\u22cf'),
    ('\\mathsfbf{N}', u'\ud5e1'),
    ('\\mathsfbf{1}', u'\ud7ed'),
    ('\\mathslbb{K}', u'\ud576'),
    ('\\hspace{1em}', u'\u2003'),
    ('\\not\\subset ', u'\u2284'),
    ('\\mathsfbf{b}', u'\ud5ef'),
    ('\\mathsfsl{P}', u'\ud617'),
    ('\\mathslbb{q}', u'\ud596'),
    ('\\mathfrak{d}', u'\ud521'),
    ('\\mathsfsl{v}', u'\ud637'),
    ('\\mathslbb{I}', u'\ud574'),
    ('\\mathfrak{e}', u'\ud522'),
    ('\\mathsfbf{C}', u'\ud5d6'),
    ('\\mathsfbf{i}', u'\ud5f6'),
    ('\\mathsfbf{u}', u'\ud602'),
    ('\\not\\supset ', u'\u2285'),
    ('\\mathslbb{f}', u'\ud58b'),
    ('\\mathfrak{c}', u'\ud520'),
    ('\\mathsfsl{a}', u'\ud622'),
    ('\\mathfrak{u}', u'\ud532'),
    ('\\mathsfbf{X}', u'\ud5eb'),
    ('\\mathslbb{U}', u'\ud580'),
    ('\\varnothing ', u'\u2205'),
    ('\\mathsfsl{F}', u'\ud60d'),
    ('\\mathfrak{n}', u'\ud52b'),
    ('\\mathsfsl{l}', u'\ud62d'),
    ('\\mathslbb{P}', u'\ud57b'),
    ('\\mathsfbf{M}', u'\ud5e0'),
    ('\\mathsfbf{s}', u'\ud600'),
    ('\\mathslbb{h}', u'\ud58d'),
    ('\\mathsfsl{Y}', u'\ud620'),
    ('\\textdollar ', u'$'),
    ('\\lmoustache ', u'\u23b0'),
    ('\\mathsfbf{Z}', u'\ud5ed'),
    ('\\mathslbb{W}', u'\ud582'),
    ('\\mathsfsl{D}', u'\ud60b'),
    ('\\mathslbb{C}', u'\ud56e'),
    ('\\mathfrak{J}', u'\ud50d'),
    ('\\nleftarrow ', u'\u219a'),
    ('\\mathsfsl{j}', u'\ud62b'),
    ('\\mathfrak{p}', u'\ud52d'),
    ('\\acute{\\eta}', u'\u03ae'),
    ('\\mathsfsl{S}', u'\ud61a'),
    ('\\mathslbb{a}', u'\ud586'),
    ('\\Lleftarrow ', u'\u21da'),
    ('\\mathsfbf{O}', u'\ud5e2'),
    ('\\mathslbb{B}', u'\ud56d'),
    ('\\mathslbb{r}', u'\ud597'),
    ('\\mathsfsl{O}', u'\ud616'),
    ('\\mathfrak{o}', u'\ud52c'),
    ('\\mathslbb{A}', u'\ud56c'),
    ('\\mathsfbf{j}', u'\ud5f7'),
    ('\\mathsfbf{t}', u'\ud601'),
    ('\\mathsl{\\Pi}', u'\ud70b'),
    ('\\mathslbb{g}', u'\ud58c'),
    ('\\mathfrak{T}', u'\ud517'),
    ('\\mathsfsl{T}', u'\ud61b'),
    ('\\mathsfsl{Z}', u'\ud621'),
    ('\\mathfrak{z}', u'\ud537'),
    ('\\mathsfbf{Y}', u'\ud5ec'),
    ('\\mathslbb{L}', u'\ud577'),
    ('\\mathslbb{d}', u'\ud589'),
    ('\\mathsfsl{M}', u'\ud614'),
    ('\\mathfrak{a}', u'\ud51e'),
    ('\\mathsfsl{s}', u'\ud634'),
    ('\\precapprox ', u'\u2ab7'),
    ('\\mathsfsl{E}', u'\ud60c'),
    ('\\mathsfbf{9}', u'\ud7f5'),
    ('\\mathsfbf{V}', u'\ud5e9'),
    ('\\mathfrak{F}', u'\ud509'),
    ('\\gtreqqless ', u'\u2a8c'),
    ('\\mathsfsl{X}', u'\ud61f'),
    ('\\mathslbb{y}', u'\ud59e'),
    ('\\mathfrak{l}', u'\ud529'),
    ('\\textdegree ', u'\xb0'),
    ('\\supsetneqq ', u'\u2acc'),
    ('\\mathsfbf{K}', u'\ud5de'),
    ('\\mathfrak{i}', u'\ud526'),
    ('\\mathsfbf{q}', u'\ud5fe'),
    ('\\mathfrak{E}', u'\ud508'),
    ('\\mathsfsl{C}', u'\ud60a'),
    ('\\mathsfsl{k}', u'\ud62c'),
    ('\\mathslbb{n}', u'\ud593'),
    ('\\mathsfbf{x}', u'\ud605'),
    ('\\mathfrak{k}', u'\ud528'),
    ('\\mathsfsl{i}', u'\ud62a'),
    ('\\mathbf{\\Xi}', u'\ud6b5'),
    ('\\eighthnote ', u'\u266a'),
    ('\\mathsfbf{f}', u'\ud5f3'),
    ('\\mathslbb{c}', u'\ud588'),
    ('\\mathfrak{P}', u'\ud513'),
    ('\\mathsfsl{N}', u'\ud615'),
    ('\\mathfrak{v}', u'\ud533'),
    ('\\mathsfsl{t}', u'\ud635'),
    ('\\mathfrak{f}', u'\ud523'),
    ('\\sqsupseteq ', u'\u2292'),
    ('\\mathslbb{H}', u'\ud573'),
    ('\\mathsfbf{8}', u'\ud7f4'),
    ('\\mathsfsl{A}', u'\ud608'),
    ('\\lesseqqgtr ', u'\u2a8b'),
    ('\\mathfrak{G}', u'\ud50a'),
    ('\\mathslbb{p}', u'\ud595'),
    ('\\circledast ', u'\u229b'),
    ('\\mathsfsl{g}', u'\ud628'),
    ('\\mathfrak{m}', u'\ud52a'),
    ('\\subsetneqq ', u'\u2acb'),
    ('\\mathsfbf{B}', u'\ud5d5'),
    ('\\mathsfbf{E}', u'\ud5d8'),
    ('\\mathsfbf{h}', u'\ud5f5'),
    ('\\hphantom{0}', u'\u2007'),
    ('\\mathslbb{e}', u'\ud58a'),
    ('\\mathsfsl{L}', u'\ud613'),
    ('\\rightarrow ', u'\u2192'),
    ('\\mathsfsl{r}', u'\ud633'),
    ('\\mathfrak{x}', u'\ud535'),
    ('\\homothetic ', u'\u223b'),
    ('\\Rightarrow ', u'\u21d2'),
    ('\\varepsilon ', u'\u025b'),
    ('\\mathslbb{J}', u'\ud575'),
    ('\\sqsubseteq ', u'\u2291'),
    ('\\mathslbb{z}', u'\ud59f'),
    ('\\mathfrak{w}', u'\ud534'),
    ('\\mathsfbf{6}', u'\ud7f2'),
    ('\\mathsfbf{L}', u'\ud5df'),
    ('\\mathsfbf{7}', u'\ud7f3'),
    ('\\mathsfbf{U}', u'\ud5e8'),
    ('\\mathsfbf{r}', u'\ud5ff'),
    ('\\mathsfsl{B}', u'\ud609'),
    ('\\mathslbb{o}', u'\ud594'),
    ('\\eqslantgtr ', u'\u2a96'),
    ('\\mathfrak{b}', u'\ud51f'),
    ('\\mathsfsl{h}', u'\ud629'),
    ('\\mathsfbf{D}', u'\ud5d7'),
    ('\\mathsfbf{A}', u'\ud5d4'),
    ('\\mathsfbf{F}', u'\ud5d9'),
    ('\\mathsfsl{G}', u'\ud60e'),
    ('\\mathsfbf{g}', u'\ud5f4'),
    ('\\mathslbb{T}', u'\ud57f'),
    ('\\hphantom{,}', u'\u2008'),
    ('\\mathslbb{l}', u'\ud591'),
    ('\\mathsfsl{U}', u'\ud61c'),
    ('\\mathsfbf{T}', u'\ud5e7'),
    ('\\mathsfbf{d}', u'\ud5f1'),
    ('\\mathsfbf{z}', u'\ud607'),
    ('\\mathfrak{N}', u'\ud511'),
    ('\\textendash ', u'\u2013'),
    ('\\mathsfsl{Q}', u'\ud618'),
    ('\\rightangle ', u'\u221f'),
    ('\\mathsfsl{f}', u'\ud627'),
    ('\\mathsfsl{K}', u'\ud612'),
    ('\\mathfrak{t}', u'\ud531'),
    ('\\ddot{\\iota}', u'\u03ca'),
    ('\\mathsfbf{y}', u'\ud606'),
    ('\\mathsfbf{S}', u'\ud5e6'),
    ('\\precapprox ', u'\u227e'),
    ('\\lessapprox ', u'\u2a85'),
    ('\\mathslbb{v}', u'\ud59b'),
    ('\\rmoustache ', u'\u23b1'),
    ('\\mathfrak{s}', u'\ud530'),
    ('\\mathsfsl{q}', u'\ud632'),
    ('\\mathsfbf{H}', u'\ud5db'),
    ('\\not\\preceq ', u'\u2aaf-00338'),
    ('\\mathslbb{E}', u'\ud570'),
    ('\\mathsfbf{n}', u'\ud5fb'),
    ('\\mathslbb{k}', u'\ud590'),
    ('\\mathfrak{X}', u'\ud51b'),
    ('\\mathsfsl{V}', u'\ud61d'),
    ('\\mathslbb{F}', u'\ud571'),
    ('\\mathfrak{K}', u'\ud50e'),
    ('\\upuparrows ', u'\u21c8'),
    ('\\mathsfbf{c}', u'\ud5f0'),
    ('\\longmapsto ', u'\u27fc'),
    ('\\mathsfsl{I}', u'\ud610'),
    ('\\mathfrak{O}', u'\ud512'),
    ('\\textemdash ', u'\u2014'),
    ('\\mathslbb{x}', u'\ud59d'),
    ('\\mathsfsl{o}', u'\ud630'),
    ('\\mathsfbf{J}', u'\ud5dd'),
    ('\\mathsfbf{5}', u'\ud7f1'),
    ('\\mathslbb{G}', u'\ud572'),
    ('\\mathsfbf{p}', u'\ud5fd'),
    ('\\mathslbb{m}', u'\ud592'),
    ('\\mathsfsl{u}', u'\ud636'),
    ('\\succapprox ', u'\u2ab8'),
    ('\\mathsfsl{z}', u'\ud63b'),
    ('\\mathsfbf{e}', u'\ud5f2'),
    ('\\mathfrak{Z}', u'\u2128'),
    ('\\mathslbb{R}', u'\ud57d'),
    ('\\mathslbb{b}', u'\ud587'),
    ('\\mathfrak{Y}', u'\ud51c'),
    ('\\mathsfsl{e}', u'\ud626'),
    ('\\mathrm{\\mu}', u'\xb5'),
    ('\\mathbf{\\Pi}', u'\ud6d1'),
    ('\\mathsl{\\Pi}', u'\ud6f1'),
    ('\\mathsfbf{0}', u'\ud7ec'),
    ('\\mathslbb{Q}', u'\ud57c'),
    ('\\mathsfsl{W}', u'\ud61e'),
    ('\\mathfrak{D}', u'\ud507'),
    ('\\mathsfsl{J}', u'\ud611'),
    ('\\mathslbb{w}', u'\ud59c'),
    ('\\mathslbb{u}', u'\ud59a'),
    ('\\mathfrak{j}', u'\ud527'),
    ('\\mathsfbf{4}', u'\ud7f0'),
    ('\\mathsfsl{p}', u'\ud631'),
    ('\\mathsfbf{W}', u'\ud5ea'),
    ('\\not\\approx ', u'\u2249'),
    ('\\mathsl{\\Xi}', u'\ud709'),
    ('\\mathsfbf{I}', u'\ud5dc'),
    ('\\mathsfbf{o}', u'\ud5fc'),
    ('\\textdegree', u'\xb0'),
    ('\\textflorin', u'\u0192'),
    ('\\"\\CYRSCHWA', u'\u04da'),
    ('\\"\\cyrschwa', u'\u04db'),
    ('\\textendash', u'\u2013'),
    ('\\textemdash', u'\u2014'),
    ('\\textbardbl', u'\u2016'),
    ('\\textdagger', u'\u2020'),
    ('\\textbullet', u'\u2022'),
    ('\\textnumero', u'\u2116'),
    ('\\textrecipe', u'\u211e'),
    ('\\textlangle', u'\u2329'),
    ('\\textrangle', u'\u232a'),
    ('\\textdagger', u'\u2020'),
    ('\\mathbit{b}', u'\ud483'),
    ('\\int\\!\\int ', u'\u222c'),
    ('\\mathscr{Y}', u'\ud4b4'),
    ('\\mathmit{R}', u'\ud4e1'),
    ('\\mathmit{E}', u'\ud4d4'),
    ('\\mathmit{T}', u'\ud4e3'),
    ('\\Elzsqspne ', u'\u22e5'),
    ('\\mathmit{h}', u'\ud4f1'),
    ('\\mathbit{l}', u'\ud48d'),
    ('\\truestate ', u'\u22a7'),
    ('\\Elzclomeg ', u'\u0277'),
    ('\\mathmit{o}', u'\ud4f8'),
    ('\\starequal ', u'\u225b'),
    ('\\mathscr{X}', u'\ud4b3'),
    ('\\backsimeq ', u'\u22cd'),
    ('\\not\\equiv ', u'\u2262'),
    ('\\mathscr{l}', u'\u2113'),
    ('\\mathmit{p}', u'\ud4f9'),
    ('\\mathbit{K}', u'\ud472'),
    ('\\mathmit{z}', u'\ud503'),
    ('\\mathbit{u}', u'\ud496'),
    ('\\mathbit{H}', u'\ud46f'),
    ('\\Elzrvbull ', u'\u25d8'),
    ('\\mathscr{D}', u'\ud49f'),
    ('\\mathscr{K}', u'\ud4a6'),
    ('\\mathmit{e}', u'\ud4ee'),
    ('\\mathbit{X}', u'\ud47f'),
    ('\\mathbit{D}', u'\ud46b'),
    ('\\mathbit{W}', u'\ud47e'),
    ('\\mathscr{a}', u'\ud4b6'),
    ('\\mathscr{z}', u'\ud4cf'),
    ('\\texttimes ', u'\xd7'),
    ('\\mathmit{f}', u'\ud4ef'),
    ('\\subsetneq ', u'\u228a'),
    ('\\mathbit{t}', u'\ud495'),
    ('\\mathbit{c}', u'\ud484'),
    ('\\mathscr{q}', u'\ud4c6'),
    ('\\tildetrpl ', u'\u224b'),
    ('\\ngeqslant ', u'\u2a7e-00338'),
    ('\\mathmit{U}', u'\ud4e4'),
    ('\\mathbit{d}', u'\ud485'),
    ('\\mathscr{B}', u'\u212c'),
    ('\\Elzvrecto ', u'\u25af'),
    ('\\mathbit{g}', u'\ud488'),
    ('\\mathscr{p}', u'\ud4c5'),
    ('\\mathmit{W}', u'\ud4e6'),
    ('\\gtrapprox ', u'\u2a86'),
    ('\\Elzinglst ', u'\u0296'),
    ('\\supseteqq ', u'\u2ac6'),
    ('\\mathmit{K}', u'\ud4da'),
    ('\\mathscr{Z}', u'\ud4b5'),
    ('\\mathmit{q}', u'\ud4fa'),
    ('\\mathbit{j}', u'\ud48b'),
    ('\\mathmit{y}', u'\ud502'),
    ('\\mathmit{F}', u'\ud4d5'),
    ('\\mathscr{g}', u'\u210a'),
    ('\\not\\simeq ', u'\u2244'),
    ('\\mathscr{c}', u'\ud4b8'),
    ('\\mathmit{V}', u'\ud4e5'),
    ('\\mathmit{b}', u'\ud4eb'),
    ('\\mathmit{x}', u'\ud501'),
    ('\\Elzminhat ', u'\u2a5f'),
    ('\\mathbit{S}', u'\ud47a'),
    ('\\mathmit{w}', u'\ud500'),
    ('\\mathscr{l}', u'\ud4c1'),
    ('\\mathscr{b}', u'\ud4b7'),
    ('\\mathbit{O}', u'\ud476'),
    ('\\mathbit{y}', u'\ud49a'),
    ('\\mathmit{G}', u'\ud4d6'),
    ('\\mathmit{m}', u'\ud4f6'),
    ('\\mathscr{O}', u'\ud4aa'),
    ('\\mathbit{k}', u'\ud48c'),
    ('\\mathbit{h}', u'\ud489'),
    ('\\mathmit{X}', u'\ud4e7'),
    ('\\mathscr{I}', u'\u2110'),
    ('\\mathmit{n}', u'\ud4f7'),
    ("\\mathrm{'Y}", u'\u038e'),
    ('\\mathbit{x}', u'\ud499'),
    ('\\mathbit{A}', u'\ud468'),
    ('\\Elzpgamma ', u'\u0263'),
    ('\\mathmit{c}', u'\ud4ec'),
    ('\\mathbit{U}', u'\ud47c'),
    ('\\mathscr{N}', u'\ud4a9'),
    ('\\mathbit{P}', u'\ud477'),
    ('\\mathscr{E}', u'\u2130'),
    ('\\mathbit{v}', u'\ud497'),
    ('\\mathscr{x}', u'\ud4cd'),
    ('\\mathscr{d}', u'\ud4b9'),
    ('\\mathmit{d}', u'\ud4ed'),
    ('\\mathmit{Q}', u'\ud4e0'),
    ('\\mathscr{t}', u'\ud4c9'),
    ('\\texttheta ', u'\u03b8'),
    ('\\mathscr{m}', u'\ud4c2'),
    ('\\mathscr{J}', u'\ud4a5'),
    ('\\mathbit{C}', u'\ud46a'),
    ('\\mathmit{S}', u'\ud4e2'),
    ('\\mathbit{o}', u'\ud490'),
    ('\\mathscr{Q}', u'\ud4ac'),
    ('\\mathmit{J}', u'\ud4d9'),
    ('\\lvertneqq ', u'\u2268-0FE00'),
    ('\\mathmit{D}', u'\ud4d3'),
    ('\\triangleq ', u'\u225c'),
    ('\\mathmit{Z}', u'\ud4e9'),
    ('\\mathmit{j}', u'\ud4f3'),
    ('\\mathbit{E}', u'\ud46c'),
    ('\\Elzreapos ', u'\u201b'),
    ('\\mathbit{G}', u'\ud46e'),
    ('\\mathbit{z}', u'\ud49b'),
    ('\\mathbit{n}', u'\ud48f'),
    ('\\mathscr{w}', u'\ud4cc'),
    ('\\mathbit{L}', u'\ud473'),
    ('\\mathscr{P}', u'\ud4ab'),
    ('\\nleqslant ', u'\u2a7d-00338'),
    ('\\mathbit{Q}', u'\ud478'),
    ('\\mathbit{m}', u'\ud48e'),
    ('\\mathscr{f}', u'\ud4bb'),
    ('\\mathbit{r}', u'\ud493'),
    ('\\mathbit{M}', u'\ud474'),
    ('\\leftarrow ', u'\u2190'),
    ('\\mathscr{R}', u'\u211b'),
    ('\\Elzlpargt ', u'\u29a0'),
    ('\\mathscr{C}', u'\ud49e'),
    ('\\mathbit{s}', u'\ud494'),
    ('\\Leftarrow ', u'\u21d0'),
    ('\\mathscr{S}', u'\ud4ae'),
    ('\\gvertneqq ', u'\u2269-0FE00'),
    ('\\mathscr{n}', u'\ud4c3'),
    ('\\mathmit{P}', u'\ud4df'),
    ('\\mathbit{F}', u'\ud46d'),
    ('\\Elztrnmlr ', u'\u0270'),
    ('\\mathscr{i}', u'\ud4be'),
    ('\\mathmit{v}', u'\ud4ff'),
    ('\\lesseqgtr ', u'\u22da'),
    ('\\Elzdlcorn ', u'\u23a3'),
    ('\\mathscr{v}', u'\ud4cb'),
    ('\\mathscr{y}', u'\ud4ce'),
    ('\\gtreqless ', u'\u22db'),
    ('\\mathscr{F}', u'\u2131'),
    ('\\mathmit{k}', u'\ud4f4'),
    ('\\Elzrttrnr ', u'\u027b'),
    ('\\mathbit{Y}', u'\ud480'),
    ('\\mathbit{J}', u'\ud471'),
    ('\\mathbit{R}', u'\ud479'),
    ('\\nparallel ', u'\u2226'),
    ('\\mathscr{r}', u'\ud4c7'),
    ('\\mathmit{O}', u'\ud4de'),
    ('\\mathscr{o}', u'\u2134'),
    ('\\rightmoon ', u'\u263e'),
    ('\\mathscr{h}', u'\ud4bd'),
    ('\\mathmit{l}', u'\ud4f5'),
    ('\\mathbit{w}', u'\ud498'),
    ('\\mathbit{i}', u'\ud48a'),
    ('\\mathscr{u}', u'\ud4ca'),
    ('\\mathmit{a}', u'\ud4ea'),
    ('\\mathbit{N}', u'\ud475'),
    ('\\mathmit{u}', u'\ud4fe'),
    ('\\Elzdshfnc ', u'\u2506'),
    ('\\mathscr{U}', u'\ud4b0'),
    ('\\therefore ', u'\u2234'),
    ('\\supsetneq ', u'\u228b'),
    ('\\mathmit{L}', u'\ud4db'),
    ('\\mathscr{A}', u'\ud49c'),
    ('\\mathscr{L}', u'\u2112'),
    ('\\mathmit{r}', u'\ud4fb'),
    ('\\mathbit{B}', u'\ud469'),
    ('\\mathscr{k}', u'\ud4c0'),
    ('\\clockoint ', u'\u2a0f'),
    ('\\textnrleg ', u'\u019e'),
    ('\\mathscr{H}', u'\u210b'),
    ('\\mathmit{A}', u'\ud4d0'),
    ('\\mathbit{I}', u'\ud470'),
    ('\\mathmit{g}', u'\ud4f0'),
    ('\\pitchfork ', u'\u22d4'),
    ('\\downarrow ', u'\u2193'),
    ('\\mathbit{a}', u'\ud482'),
    ('\\Elzreglst ', u'\u0295'),
    ('\\mathscr{T}', u'\ud4af'),
    ('\\subseteqq ', u'\u2ac5'),
    ('\\mathmit{B}', u'\ud4d1'),
    ('\\Downarrow ', u'\u21d3'),
    ('\\mathbit{q}', u'\ud492'),
    ('\\mathscr{j}', u'\ud4bf'),
    ('\\mathbit{e}', u'\ud486'),
    ('\\Elzpupsil ', u'\u028a'),
    ('\\mathscr{M}', u'\u2133'),
    ('\\mathmit{H}', u'\ud4d7'),
    ('\\mathscr{G}', u'\ud4a2'),
    ('\\mathbit{T}', u'\ud47b'),
    ('\\textTheta ', u'\u03f4'),
    ('\\mathmit{I}', u'\ud4d8'),
    ('\\mathbit{Z}', u'\ud481'),
    ('\\mathbit{f}', u'\ud487'),
    ('\\texthvlig ', u'\u0195'),
    ('\\mathscr{W}', u'\ud4b2'),
    ('\\mathbit{p}', u'\ud491'),
    ('\\nsupseteqq', u'\u2ac6-00338'),
    ('\\mathbit{O}', u'\ud72d'),
    ('\\mathmit{M}', u'\ud4dc'),
    ('\\mathscr{e}', u'\u212f'),
    ('\\mathmit{t}', u'\ud4fd'),
    ('\\mathmit{s}', u'\ud4fc'),
    ('\\estimates ', u'\u2259'),
    ('\\mathscr{V}', u'\ud4b1'),
    ('\\mathscr{s}', u'\ud4c8'),
    ('\\mathmit{N}', u'\ud4dd'),
    ('\\mathmit{Y}', u'\ud4e8'),
    ('\\textturnk ', u'\u029e'),
    ('\\backprime ', u'\u2035'),
    ('\\mathmit{C}', u'\ud4d2'),
    ('\\mathbit{V}', u'\ud47d'),
    ('\\mathmit{i}', u'\ud4f2'),
    ('\\texttimes', u'\xd7'),
    ('\\CYRCHRDSC', u'\u04b6'),
    ('\\cyrchrdsc', u'\u04b7'),
    ('\\CYRCHVCRS', u'\u04b8'),
    ('\\cyrchvcrs', u'\u04b9'),
    ('\\CYRCHLDSC', u'\u04cb'),
    ('\\cyrchldsc', u'\u04cc'),
    ('\\CYRABHDZE', u'\u04e0'),
    ('\\cyrabhdze', u'\u04e1'),
    ('\\"\\CYREREV', u'\u04ec'),
    ('\\"\\cyrerev', u'\u04ed'),
    ('\\textnaira', u'\u20a6'),
    ('\\textblank', u'\u2422'),
    ('\\copyright', u'\xa9'),
    ('\\mathsf{K}', u'\ud5aa'),
    ('\\ding{197}', u'\u2785'),
    ('\\mathsl{i}', u'\ud456'),
    ('\\mathtt{f}', u'\ud68f'),
    ('\\mathbf{v}', u'\ud42f'),
    ('\\ding{229}', u'\u27a5'),
    ('\\supseteq ', u'\u2287'),
    ('\\mathtt{3}', u'\ud7f9'),
    ('\\ding{124}', u'\u275c'),
    ('\\allequal ', u'\u224c'),
    ('\\mathbf{x}', u'\ud431'),
    ('\\ding{122}', u'\u275a'),
    ('\\mathbb{P}', u'\u2119'),
    ('\\mathbf{Q}', u'\ud410'),
    ('\\ding{178}', u'\u2466'),
    ('\\mathsl{L}', u'\ud43f'),
    ('\\ding{186}', u'\u277a'),
    ('\\mathtt{U}', u'\ud684'),
    ('\\Elzsqfnw ', u'\u2519'),
    ('\\ding{218}', u'\u279a'),
    ('\\mathsf{O}', u'\ud5ae'),
    ('\\mathtt{C}', u'\ud672'),
    ('\\mathbb{B}', u'\ud539'),
    ('\\ding{250}', u'\u27ba'),
    ('\\varsigma ', u'\u03c2'),
    ('\\ding{101}', u'\u2745'),
    ('\\mathbf{U}', u'\ud414'),
    ('\\Elzverti ', u'\u02cc'),
    ('\\mathsf{u}', u'\ud5ce'),
    ('\\ding{238}', u'\u27ae'),
    ('\\mathsl{b}', u'\ud44f'),
    ('\\mathbb{h}', u'\ud559'),
    ('\\mathbb{2}', u'\ud7da'),
    ('\\ding{175}', u'\u2463'),
    ('\\ding{165}', u'\u2765'),
    ('\\mathsf{J}', u'\ud5a9'),
    ('\\mathbf{o}', u'\ud428'),
    ('\\mathbb{6}', u'\ud7de'),
    ('\\mathbf{e}', u'\ud41e'),
    ('\\mathtt{V}', u'\ud685'),
    ('\\ding{207}', u'\u278f'),
    ('\\mathsf{D}', u'\ud5a3'),
    ('\\ding{239}', u'\u27af'),
    ('\\succnsim ', u'\u22e9'),
    ('\\mathsl{r}', u'\ud45f'),
    ('\\mathbb{A}', u'\ud538'),
    ('\\ding{100}', u'\u2744'),
    ('\\mathbf{1}', u'\ud7cf'),
    ('\\mathsl{E}', u'\ud438'),
    ('\\mathbb{g}', u'\ud558'),
    ('\\mathsf{4}', u'\ud7e6'),
    ('\\ding{164}', u'\u2764'),
    ('\\mathbf{M}', u'\ud40c'),
    ('\\ding{196}', u'\u2784'),
    ('\\mathtt{q}', u'\ud69a'),
    ('\\mathbb{R}', u'\u211d'),
    ('\\mathbb{L}', u'\ud543'),
    ('\\mathsf{A}', u'\ud5a0'),
    ('\\ding{111}', u'\u274f'),
    ('\\mathbf{j}', u'\ud423'),
    ('\\mathtt{y}', u'\ud6a2'),
    ('\\mathbb{W}', u'\ud54e'),
    ('\\mathtt{1}', u'\ud7f7'),
    ('\\mathbb{r}', u'\ud563'),
    ('\\ding{170}', u'\u2665'),
    ('\\mathsf{2}', u'\ud7e4'),
    ('\\leqslant ', u'\u2a7d'),
    ('\\mathtt{T}', u'\ud683'),
    ('\\Elzpscrv ', u'\u028b'),
    ('\\ding{217}', u'\u2799'),
    ('\\mathtt{z}', u'\ud6a3'),
    ('\\mathsf{F}', u'\ud5a5'),
    ('\\ding{249}', u'\u27b9'),
    ('\\mathbb{m}', u'\ud55e'),
    ('\\mathsf{l}', u'\ud5c5'),
    ('\\mathbb{1}', u'\ud7d9'),
    ('\\mathbf{Y}', u'\ud418'),
    ('\\ding{180}', u'\u2468'),
    ('\\not\\prec ', u'\u2280'),
    ('\\mathsf{g}', u'\ud5c0'),
    ('\\mathtt{o}', u'\ud698'),
    ('\\mathsf{a}', u'\ud5ba'),
    ('\\mathsl{e}', u'\ud452'),
    ('\\mathbf{0}', u'\ud7ce'),
    ('\\ding{121}', u'\u2759'),
    ('\\mathbb{e}', u'\ud556'),
    ('\\mathsl{d}', u'\ud451'),
    ('\\ding{168}', u'\u2663'),
    ('\\mathbb{t}', u'\ud565'),
    ('\\mathsf{w}', u'\ud5d0'),
    ('\\ding{185}', u'\u2779'),
    ('\\not\\succ ', u'\u2281'),
    ('\\ding{195}', u'\u2783'),
    ('\\mathbf{g}', u'\ud420'),
    ('\\Elxsqcup ', u'\u2a06'),
    ('\\mathsf{P}', u'\ud5af'),
    ('\\setminus ', u'\u2216'),
    ('\\mathtt{p}', u'\ud699'),
    ('\\ding{227}', u'\u27a3'),
    ('\\ding{173}', u'\u2461'),
    ('\\mathbb{M}', u'\ud544'),
    ('\\ding{108}', u'\u25cf'),
    ('\\mathbf{c}', u'\ud41c'),
    ('\\mathsf{1}', u'\ud7e3'),
    ('\\mathsl{G}', u'\ud43a'),
    ('\\mathbb{s}', u'\ud564'),
    ('\\mathsf{f}', u'\ud5bf'),
    ('\\mathsl{n}', u'\ud45b'),
    ('\\ding{184}', u'\u2778'),
    ('\\mathtt{e}', u'\ud68e'),
    ('\\ding{216}', u'\u2798'),
    ('\\mathbf{C}', u'\ud402'),
    ('\\textcent ', u'\xa2'),
    ('\\mathsf{E}', u'\ud5a4'),
    ('\\original ', u'\u22b6'),
    ('\\ding{248}', u'\u27b8'),
    ('\\mathsf{k}', u'\ud5c4'),
    ('\\Elzrarrx ', u'\u2947'),
    ('\\mathbb{X}', u'\ud54f'),
    ('\\mathsf{v}', u'\ud5cf'),
    ('\\ding{163}', u'\u2763'),
    ('\\mathtt{6}', u'\ud7fc'),
    ('\\mathtt{J}', u'\ud679'),
    ('\\mathbf{A}', u'\ud400'),
    ('\\ding{205}', u'\u278d'),
    ('\\sqsubset ', u'\u228f'),
    ('\\mathbb{0}', u'\ud7d8'),
    ('\\mathtt{n}', u'\ud697'),
    ('\\ding{120}', u'\u2758'),
    ('\\ding{237}', u'\u27ad'),
    ('\\mathbf{z}', u'\ud433'),
    ('\\mathsf{h}', u'\ud5c1'),
    ('\\ding{162}', u'\u2762'),
    ('\\Elzpbgam ', u'\u0264'),
    ('\\mathsl{z}', u'\ud467'),
    ('\\mathsf{e}', u'\ud5be'),
    ('\\ding{194}', u'\u2782'),
    ('\\barwedge ', u'\u2305'),
    ('\\ding{244}', u'\u27b4'),
    ('\\mathsl{P}', u'\ud443'),
    ('\\mathbf{Z}', u'\ud419'),
    ('\\mathbb{Q}', u'\u211a'),
    ('\\Elzdyogh ', u'\u02a4'),
    ('\\mathbf{B}', u'\ud401'),
    ('\\circledS ', u'\u24c8'),
    ('\\mathbf{8}', u'\ud7d6'),
    ('\\mathbb{J}', u'\ud541'),
    ('\\ding{109}', u'\u274d'),
    ('\\mathbb{p}', u'\ud561'),
    ('\\mathsl{f}', u'\ud453'),
    ('\\mathbf{h}', u'\ud421'),
    ('\\mathsl{k}', u'\ud458'),
    ('\\mathtt{O}', u'\ud67e'),
    ('\\mathsf{N}', u'\ud5ad'),
    ('\\mathtt{d}', u'\ud68d'),
    ('\\mathbf{s}', u'\ud42c'),
    ('\\mathbf{F}', u'\ud405'),
    ('\\mathsf{L}', u'\ud5ab'),
    ('\\precneqq ', u'\u2ab5'),
    ('\\ding{247}', u'\u27b7'),
    ('\\mathbb{I}', u'\ud540'),
    ('\\mathsf{q}', u'\ud5ca'),
    ('\\mathsl{v}', u'\ud463'),
    ('\\mathbf{9}', u'\ud7d7'),
    ('\\mathbb{o}', u'\ud560'),
    ('\\mathsf{d}', u'\ud5bd'),
    ('\\mathsl{w}', u'\ud464'),
    ('\\mathsl{I}', u'\ud43c'),
    ('\\Elztrnrl ', u'\u027a'),
    ('\\mathbb{3}', u'\ud7db'),
    ('\\mathtt{S}', u'\ud682'),
    ('\\mathsl{s}', u'\ud460'),
    ('\\ding{204}', u'\u278c'),
    ('\\cyrchar\\C', u'\u030f'),
    ('\\ding{110}', u'\u25a0'),
    ('\\parallel ', u'\u2225'),
    ('\\ding{236}', u'\u27ac'),
    ('\\intercal ', u'\u22ba'),
    ('\\mathbb{T}', u'\ud54b'),
    ('\\mathbf{l}', u'\ud425'),
    ('\\mathbb{z}', u'\ud56b'),
    ('\\mathbb{d}', u'\ud555'),
    ('\\ding{183}', u'\u2777'),
    ('\\ding{193}', u'\u2781'),
    ('\\mathtt{b}', u'\ud68b'),
    ('\\not\\apid ', u'\u224b-00338'),
    ('\\mathsf{R}', u'\ud5b1'),
    ('\\ding{225}', u'\u27a1'),
    ('\\mathsl{o}', u'\ud45c'),
    ('\\mathsl{Y}', u'\ud44c'),
    ('\\mathsf{U}', u'\ud5b4'),
    ('\\mathbb{K}', u'\ud542'),
    ('\\mathsf{t}', u'\ud5cd'),
    ('\\mathbf{R}', u'\ud411'),
    ('\\mathsl{U}', u'\ud448'),
    ('\\ding{118}', u'\u2756'),
    ('\\mathbb{9}', u'\ud7e1'),
    ('\\ding{171}', u'\u2660'),
    ('\\mathbb{q}', u'\ud562'),
    ('\\ding{182}', u'\u2776'),
    ('\\mathtt{Q}', u'\ud680'),
    ('\\mathtt{w}', u'\ud6a0'),
    ('\\mathsf{C}', u'\ud5a2'),
    ('\\mathsf{T}', u'\ud5b3'),
    ('\\ding{246}', u'\u27b6'),
    ('\\mathbf{V}', u'\ud415'),
    ('\\mathbb{V}', u'\ud54d'),
    ('\\ding{161}', u'\u2761'),
    ('\\mathtt{R}', u'\ud681'),
    ('\\lnapprox ', u'\u2a89'),
    ('\\mathbf{J}', u'\ud409'),
    ('\\ding{203}', u'\u278b'),
    ('\\mathtt{x}', u'\ud6a1'),
    ('\\ding{235}', u'\u27ab'),
    ('\\mathsl{N}', u'\ud441'),
    ('\\mathsf{X}', u'\ud5b7'),
    ('\\mathbb{U}', u'\ud54c'),
    ('\\ding{119}', u'\u25d7'),
    ('\\ding{177}', u'\u2465'),
    ('\\mathsf{9}', u'\ud7eb'),
    ('\\mathtt{G}', u'\ud676'),
    ('\\mathbb{N}', u'\u2115'),
    ('\\mathsl{K}', u'\ud43e'),
    ('\\geqslant ', u'\u2a7e'),
    ('\\ding{192}', u'\u2780'),
    ('\\mathbf{N}', u'\ud40d'),
    ('\\mathtt{m}', u'\ud696'),
    ('\\mathsl{R}', u'\ud445'),
    ('\\mathsf{M}', u'\ud5ac'),
    ('\\mathbf{G}', u'\ud406'),
    ('\\ding{107}', u'\u274b'),
    ('\\mathsf{s}', u'\ud5cc'),
    ('\\curlyvee ', u'\u22ce'),
    ('\\mathbf{O}', u'\ud40e'),
    ('\\Elzschwa ', u'\u0259'),
    ('\\mathbb{8}', u'\ud7e0'),
    ('\\mathbf{n}', u'\ud427'),
    ('\\ding{230}', u'\u27a6'),
    ('\\mathtt{v}', u'\ud69f'),
    ('\\mathsl{Z}', u'\ud44d'),
    ('\\mathsf{S}', u'\ud5b2'),
    ('\\ding{245}', u'\u27b5'),
    ('\\mathsl{q}', u'\ud45e'),
    ('\\mathbb{G}', u'\ud53e'),
    ('\\mathsl{D}', u'\ud437'),
    ('\\mathsf{p}', u'\ud5c9'),
    ('\\ding{106}', u'\u274a'),
    ('\\mathsl{a}', u'\ud44e'),
    ('\\mathtt{2}', u'\ud7f8'),
    ('\\mathbf{7}', u'\ud7d5'),
    ('\\multimap ', u'\u22b8'),
    ('\\ding{226}', u'\u27a2'),
    ('\\mathtt{E}', u'\ud674'),
    ('\\ding{202}', u'\u278a'),
    ('\\mathtt{k}', u'\ud694'),
    ('\\urcorner ', u'\u231d'),
    ('\\mathsl{F}', u'\ud439'),
    ('\\mathsl{T}', u'\ud447'),
    ('\\ding{234}', u'\u27aa'),
    ('\\mathbf{S}', u'\ud412'),
    ('\\mathsf{B}', u'\ud5a1'),
    ('\\not\\cong ', u'\u2247'),
    ('\\mathtt{K}', u'\ud67a'),
    ('\\mathbb{x}', u'\ud569'),
    ('\\mathsf{y}', u'\ud5d2'),
    ('\\mathsl{B}', u'\ud435'),
    ('\\mathtt{P}', u'\ud67f'),
    ('\\mathsl{j}', u'\ud457'),
    ('\\mathtt{l}', u'\ud695'),
    ('\\ulcorner ', u'\u231c'),
    ('\\ding{223}', u'\u279f'),
    ('\\mkern4mu ', u'\u205f'),
    ('\\mathtt{a}', u'\ud68a'),
    ('\\Elzdefas ', u'\u29cb'),
    ('\\mathsf{z}', u'\ud5d3'),
    ('\\Elztrnsa ', u'\u0252'),
    ('\\mathbb{7}', u'\ud7df'),
    ('\\ding{179}', u'\u2467'),
    ('\\Elzsqfse ', u'\u25ea'),
    ('\\mathbb{w}', u'\ud568'),
    ('\\not\\doteq', u'\u2250-00338'),
    ('\\mathsl{M}', u'\ud440'),
    ('\\mathsl{J}', u'\ud43d'),
    ('\\ding{212}', u'\u2794'),
    ('\\mathsf{Z}', u'\ud5b9'),
    ('\\mathsf{I}', u'\ud5a8'),
    ('\\mathsf{o}', u'\ud5c8'),
    ('\\mathbb{b}', u'\ud553'),
    ('\\Elzsbrhr ', u'\u02d2'),
    ('\\mathbf{6}', u'\ud7d4'),
    ('\\ding{228}', u'\u27a4'),
    ('\\mathsf{x}', u'\ud5d1'),
    ('\\mathtt{9}', u'\ud7ff'),
    ('\\mathbf{p}', u'\ud429'),
    ('\\ding{114}', u'\u2752'),
    ('\\mathtt{F}', u'\ud675'),
    ('\\ding{191}', u'\u277f'),
    ('\\ding{201}', u'\u2789'),
    ('\\mathbf{D}', u'\ud403'),
    ('\\mathsf{6}', u'\ud7e8'),
    ('\\ding{233}', u'\u27a9'),
    ('\\ElzRlarr ', u'\u2942'),
    ('\\ding{172}', u'\u2460'),
    ('\\mathbb{S}', u'\ud54a'),
    ('\\mathsf{Y}', u'\ud5b8'),
    ('\\mathsf{7}', u'\ud7e9'),
    ('\\mathbb{y}', u'\ud56a'),
    ('\\ding{190}', u'\u277e'),
    ('\\mathtt{Y}', u'\ud688'),
    ('\\ding{222}', u'\u279e'),
    ('\\mathsl{V}', u'\ud449'),
    ('\\ding{254}', u'\u27be'),
    ('\\ding{105}', u'\u2749'),
    ('\\mathbb{Z}', u'\u2124'),
    ('\\mathtt{D}', u'\ud673'),
    ('\\mathbf{y}', u'\ud432'),
    ('\\mathtt{8}', u'\ud7fe'),
    ('\\mathtt{Z}', u'\ud689'),
    ('\\mathsl{g}', u'\ud454'),
    ('\\mathsl{l}', u'\ud459'),
    ('\\ding{211}', u'\u2793'),
    ('\\mathbf{K}', u'\ud40a'),
    ('\\ding{243}', u'\u27b3'),
    ('\\ding{104}', u'\u2748'),
    ('\\mathtt{c}', u'\ud68c'),
    ('\\Elzhlmrk ', u'\u02d1'),
    ('\\mathbf{5}', u'\ud7d3'),
    ('\\mathbb{c}', u'\ud554'),
    ('\\mathbf{i}', u'\ud422'),
    ('\\ding{181}', u'\u2469'),
    ('\\mathsl{t}', u'\ud461'),
    ('\\subseteq ', u'\u2286'),
    ('\\mathsl{O}', u'\ud442'),
    ('\\mathtt{u}', u'\ud69e'),
    ('\\mathbf{t}', u'\ud42d'),
    ('\\ding{232}', u'\u27a8'),
    ('\\succneqq ', u'\u2ab6'),
    ('\\doteqdot ', u'\u2251'),
    ('\\mathsl{x}', u'\ud465'),
    ('\\mathbb{n}', u'\ud55f'),
    ('\\Elzltlmr ', u'\u0271'),
    ('\\varkappa ', u'\u03f0'),
    ('\\Elztdcol ', u'\u2af6'),
    ('\\mathbf{r}', u'\ud42b'),
    ('\\mathsf{r}', u'\ud5cb'),
    ('\\Elxuplus ', u'\u2a04'),
    ('\\mathtt{X}', u'\ud687'),
    ('\\mathbb{C}', u'\u2102'),
    ('\\Elzddfnc ', u'\u2999'),
    ('\\ding{221}', u'\u279d'),
    ('\\boxminus ', u'\u229f'),
    ('\\mathsf{8}', u'\ud7ea'),
    ('\\Elzsbbrg ', u'\u032a'),
    ('\\ding{253}', u'\u27bd'),
    ('\\mathbb{O}', u'\ud546'),
    ('\\mathsf{W}', u'\ud5b6'),
    ('\\mathsf{j}', u'\ud5c3'),
    ('\\mathbf{X}', u'\ud417'),
    ('\\Elzcirfr ', u'\u25d1'),
    ('\\mathsl{c}', u'\ud450'),
    ('\\ding{174}', u'\u2462'),
    ('\\Elzopeno ', u'\u0254'),
    ('\\mathbb{5}', u'\ud7dd'),
    ('\\mathsl{H}', u'\ud43b'),
    ('\\mathbf{a}', u'\ud41a'),
    ('\\mathbb{u}', u'\ud566'),
    ('\\mathbf{q}', u'\ud42a'),
    ('\\ding{169}', u'\u2666'),
    ('\\mathtt{j}', u'\ud693'),
    ('\\mathtt{4}', u'\ud7fa'),
    ('\\mathtt{7}', u'\ud7fd'),
    ('\\mathtt{M}', u'\ud67c'),
    ('\\ding{210}', u'\u2792'),
    ('\\recorder ', u'\u2315'),
    ('\\mathsf{i}', u'\ud5c2'),
    ('\\mathtt{s}', u'\ud69c'),
    ('\\mathsf{G}', u'\ud5a6'),
    ('\\ElzTimes ', u'\u2a2f'),
    ('\\ding{242}', u'\u27b2'),
    ('\\mathtt{0}', u'\ud7f6'),
    ('\\ding{117}', u'\u25c6'),
    ('\\ding{125}', u'\u275d'),
    ('\\mathbf{k}', u'\ud424'),
    ('\\mathbf{4}', u'\ud7d2'),
    ('\\mathbf{b}', u'\ud41b'),
    ('\\ding{189}', u'\u277d'),
    ('\\ding{199}', u'\u2787'),
    ('\\mathtt{t}', u'\ud69d'),
    ('\\ding{231}', u'\u27a7'),
    ('\\mathsf{3}', u'\ud7e5'),
    ('\\mathsf{V}', u'\ud5b5'),
    ('\\mathsf{b}', u'\ud5bb'),
    ('\\mathsf{m}', u'\ud5c6'),
    ('\\mathsl{A}', u'\ud434'),
    ('\\mathsl{m}', u'\ud45a'),
    ('\\approxeq ', u'\u224a'),
    ('\\mathbb{Y}', u'\ud550'),
    ('\\aquarius ', u'\u2652'),
    ('\\mathbf{L}', u'\ud40b'),
    ('\\mathsf{0}', u'\ud7e2'),
    ('\\mathsf{5}', u'\ud7e7'),
    ('\\ding{200}', u'\u2788'),
    ('\\ding{188}', u'\u277c'),
    ('\\mathtt{i}', u'\ud692'),
    ('\\ding{220}', u'\u279c'),
    ('\\lrcorner ', u'\u231f'),
    ('\\mathsl{Q}', u'\ud444'),
    ('\\mathbf{d}', u'\ud41d'),
    ('\\mathbf{H}', u'\ud407'),
    ('\\mathsf{Q}', u'\ud5b0'),
    ('\\mathbb{D}', u'\ud53b'),
    ('\\ding{252}', u'\u27bc'),
    ('\\mathbf{P}', u'\ud40f'),
    ('\\mathtt{H}', u'\ud677'),
    ('\\ding{103}', u'\u2747'),
    ('\\ding{224}', u'\u27a0'),
    ('\\Elzcirfl ', u'\u25d0'),
    ('\\mathbb{j}', u'\ud55b'),
    ('\\mathsl{u}', u'\ud462'),
    ('\\ding{167}', u'\u2767'),
    ('\\mathbb{4}', u'\ud7dc'),
    ('\\mathtt{N}', u'\ud67d'),
    ('\\ding{209}', u'\u2791'),
    ('\\mathtt{r}', u'\ud69b'),
    ('\\llcorner ', u'\u231e'),
    ('\\mathbb{i}', u'\ud55a'),
    ('\\ding{241}', u'\u27b1'),
    ('\\ding{126}', u'\u275e'),
    ('\\mathsl{S}', u'\ud446'),
    ('\\ding{102}', u'\u2746'),
    ('\\mathbf{3}', u'\ud7d1'),
    ('\\Elzsblhr ', u'\u02d3'),
    ('\\mathbb{a}', u'\ud552'),
    ('\\ding{176}', u'\u2464'),
    ('\\mathbf{T}', u'\ud413'),
    ('\\ding{166}', u'\u2766'),
    ('\\mathsf{c}', u'\ud5bc'),
    ('\\mathtt{A}', u'\ud670'),
    ('\\mathsl{y}', u'\ud466'),
    ('\\ding{198}', u'\u2786'),
    ('\\mathbf{W}', u'\ud416'),
    ('\\mathtt{g}', u'\ud690'),
    ('\\mathsl{W}', u'\ud44a'),
    ('\\ding{115}', u'\u25b2'),
    ('\\mathbb{F}', u'\ud53d'),
    ('\\Elzverts ', u'\u02c8'),
    ('\\ding{113}', u'\u2751'),
    ('\\Elzcirfb ', u'\u25d2'),
    ('\\mathtt{I}', u'\ud678'),
    ('\\mathbb{l}', u'\ud55d'),
    ('\\mathbf{2}', u'\ud7d0'),
    ('\\mathbf{m}', u'\ud426'),
    ('\\mathtt{L}', u'\ud67b'),
    ('\\mathbb{f}', u'\ud557'),
    ('\\mathbf{u}', u'\ud42e'),
    ('\\mkern1mu ', u'\u200a'),
    ('\\mathtt{h}', u'\ud691'),
    ('\\ding{219}', u'\u279b'),
    ('\\mathsf{H}', u'\ud5a7'),
    ('\\mathbf{E}', u'\ud404'),
    ('\\ding{251}', u'\u27bb'),
    ('\\mathbb{E}', u'\ud53c'),
    ('\\lazysinv ', u'\u223e'),
    ('\\ElzrLarr ', u'\u2944'),
    ('\\mathsf{n}', u'\ud5c7'),
    ('\\mathbb{H}', u'\u210d'),
    ('\\mathsl{C}', u'\ud436'),
    ('\\ding{112}', u'\u2750'),
    ('\\ding{206}', u'\u278e'),
    ('\\mathbb{k}', u'\ud55c'),
    ('\\sqsupset ', u'\u2290'),
    ('\\gnapprox ', u'\u2a8a'),
    ('\\mathtt{W}', u'\ud686'),
    ('\\ding{208}', u'\u2790'),
    ('\\mathtt{5}', u'\ud7fb'),
    ('\\mathbf{f}', u'\ud41f'),
    ('\\ding{116}', u'\u25bc'),
    ('\\boxtimes ', u'\u22a0'),
    ('\\mathbf{w}', u'\ud430'),
    ('\\mathbf{I}', u'\ud408'),
    ('\\mathsl{X}', u'\ud44b'),
    ('\\ding{123}', u'\u275b'),
    ('\\mathsl{p}', u'\ud45d'),
    ('\\mathbb{v}', u'\ud567'),
    ('\\mathtt{B}', u'\ud671'),
    ('\\ding{187}', u'\u277b'),
    ('\\textcent', u'\xa2'),
    ('\\textlnot', u'\xac'),
    ('\\CYRUSHRT', u'\u040e'),
    ('\\CYRISHRT', u'\u0419'),
    ('\\CYRHRDSN', u'\u042a'),
    ('\\CYRSFTSN', u'\u042c'),
    ('\\cyrishrt', u'\u0439'),
    ('\\cyrhrdsn', u'\u044a'),
    ('\\cyrsftsn', u'\u044c'),
    ('\\cyrushrt', u'\u045e'),
    ('\\C\\CYRIZH', u'\u0476'),
    ('\\C\\cyrizh', u'\u0477'),
    ('\\CYRRTICK', u'\u048e'),
    ('\\cyrrtick', u'\u048f'),
    ('\\CYRGHCRS', u'\u0492'),
    ('\\cyrghcrs', u'\u0493'),
    ('\\CYRZHDSC', u'\u0496'),
    ('\\cyrzhdsc', u'\u0497'),
    ('\\CYRKVCRS', u'\u049c'),
    ('\\cyrkvcrs', u'\u049d'),
    ('\\CYRKHCRS', u'\u049e'),
    ('\\cyrkhcrs', u'\u049f'),
    ('\\CYRKBEAK', u'\u04a0'),
    ('\\cyrkbeak', u'\u04a1'),
    ('\\CYRABHHA', u'\u04a8'),
    ('\\cyrabhha', u'\u04a9'),
    ('\\CYRYHCRS', u'\u04b0'),
    ('\\cyryhcrs', u'\u04b1'),
    ('\\CYRTETSE', u'\u04b4'),
    ('\\cyrtetse', u'\u04b5'),
    ('\\CYRABHCH', u'\u04bc'),
    ('\\cyrabhch', u'\u04bd'),
    ('\\CYRSCHWA', u'\u04d8'),
    ('\\cyrschwa', u'\u04d9'),
    ('\\"\\CYRERY', u'\u04f8'),
    ('\\"\\cyrery', u'\u04f9'),
    ('\\CYRHHCRS', u'\u04fe'),
    ('\\cyrhhcrs', u'\u04ff'),
    ('\\textbaht', u'\u0e3f'),
    ('\\textlira', u'\u20a4'),
    ('\\textdong', u'\u20ab'),
    ('\\texteuro', u'\u20ac'),
    ('\\textpeso', u'\u20b1'),
    ('\\ding{58}', u'\u271a'),
    ('\\ding{90}', u'\u273a'),
    ('\\Elzbtdl ', u'\u026c'),
    ('\\Elzinvv ', u'\u028c'),
    ('\\nwarrow ', u'\u2196'),
    ('\\ding{69}', u'\u2725'),
    ('\\scorpio ', u'\u264f'),
    ('\\partial ', u'\u2202'),
    ('\\ding{36}', u'\u2704'),
    ('\\Elzinvw ', u'\u028d'),
    ('\\ding{68}', u'\u2724'),
    ('\\Elzrtls ', u'\u0282'),
    ('\\ding{72}', u'\u2605'),
    ('\\ding{47}', u'\u270f'),
    ('\\ding{79}', u'\u272f'),
    ('\\Elzrtll ', u'\u026d'),
    ('\\ding{46}', u'\u270e'),
    ('\\ding{78}', u'\u272e'),
    ('\\ding{37}', u'\u260e'),
    ('\\between ', u'\u226c'),
    ('\\ding{57}', u'\u2719'),
    ('\\Elzpalh ', u'\u0321'),
    ('\\ding{89}', u'\u2739'),
    ('\\jupiter ', u'\u2643'),
    ('\\nearrow ', u'\u2197'),
    ('\\ding{56}', u'\u2718'),
    ('\\Elroang ', u'\u2986'),
    ('\\ding{88}', u'\u2738'),
    ('\\partial ', u'\ud7c3'),
    ('\\Elzrtld ', u'\u0256'),
    ('\\bigcirc ', u'\u25ef'),
    ('\\natural ', u'\u266e'),
    ('\\lessgtr ', u'\u2276'),
    ('\\ding{35}', u'\u2703'),
    ('\\ding{67}', u'\u2723'),
    ('\\not\\sim ', u'\u2241'),
    ('\\ding{99}', u'\u2743'),
    ('\\lessdot ', u'\u22d6'),
    ('\\ding{34}', u'\u2702'),
    ('\\nexists ', u'\u2204'),
    ('\\swarrow ', u'\u2199'),
    ('\\ding{66}', u'\u2722'),
    ('\\Upsilon ', u'\u03a5'),
    ('\\upsilon ', u'\u03c5'),
    ('\\ding{45}', u'\u270d'),
    ('\\ding{77}', u'\u272d'),
    ('\\diamond ', u'\u22c4'),
    ('\\Elztrnm ', u'\u026f'),
    ('\\ding{44}', u'\u270c'),
    ('\\ding{76}', u'\u272c'),
    ('\\bigcirc ', u'\u25cb'),
    ('\\diamond ', u'\u2662'),
    ('\\tone{55}', u'\u02e5'),
    ('\\ding{55}', u'\u2717'),
    ('\\searrow ', u'\u2198'),
    ('\\ding{87}', u'\u2737'),
    ('\\Elztrnh ', u'\u0265'),
    ('\\ding{54}', u'\u2716'),
    ('\\fbox{~~}', u'\u25ad'),
    ('\\ding{86}', u'\u2736'),
    ('\\textphi ', u'\u0278'),
    ('\\ding{33}', u'\u2701'),
    ('\\ding{65}', u'\u2721'),
    ('\\ding{97}', u'\u2741'),
    ('\\ding{64}', u'\u2720'),
    ('\\textyen ', u'\xa5'),
    ('\\ding{84}', u'\u2734'),
    ('\\ding{96}', u'\u2740'),
    ('\\ding{49}', u'\u2711'),
    ('\\Elztrny ', u'\u028e'),
    ('\\not\\geq ', u'\u2271'),
    ('\\ding{75}', u'\u272b'),
    ('\\Elztrnr ', u'\u0279'),
    ('\\ding{98}', u'\u2742'),
    ('\\Elztrnt ', u'\u0287'),
    ('\\uparrow ', u'\u2191'),
    ('\\Elztesh ', u'\u02a7'),
    ('\\ding{74}', u'\u272a'),
    ('\\Uparrow ', u'\u21d1'),
    ('\\digamma ', u'\u03dd'),
    ('\\tone{33}', u'\u02e7'),
    ('\\ding{40}', u'\u2708'),
    ('\\ding{50}', u'\u2712'),
    ('\\ding{53}', u'\u2715'),
    ('\\partial ', u'\ud715'),
    ('\\ding{85}', u'\u2735'),
    ('\\Elzxrat ', u'\u211e'),
    ('\\mercury ', u'\u263f'),
    ('\\Elorarr ', u'\u2941'),
    ('\\Upsilon ', u'\u03d2'),
    ('\\ding{52}', u'\u2714'),
    ('\\Elolarr ', u'\u2940'),
    ('\\Elzltln ', u'\u0272'),
    ('\\Elztfnc ', u'\u2980'),
    ('\\ElzCint ', u'\u2a0d'),
    ('\\Elzyogh ', u'\u0292'),
    ('\\ding{63}', u'\u271f'),
    ('\\backsim ', u'\u223d'),
    ('\\ding{95}', u'\u273f'),
    ('\\Digamma ', u'\u03dc'),
    ('\\Elzsqfr ', u'\u25e8'),
    ('\\Elzrtlr ', u'\u027d'),
    ('\\ding{62}', u'\u271e'),
    ('\\ding{94}', u'\u273e'),
    ('\\Elztrna ', u'\u0250'),
    ('\\gtrless ', u'\u2277'),
    ('\\ding{48}', u'\u2710'),
    ('\\ding{41}', u'\u2709'),
    ('\\Elzrtlz ', u'\u0290'),
    ('\\ding{73}', u'\u2729'),
    ('\\partial ', u'\ud789'),
    ('\\lozenge ', u'\u25ca'),
    ('\\Elzlmrk ', u'\u02d0'),
    ('\\ding{43}', u'\u261e'),
    ('\\ding{51}', u'\u2713'),
    ('\\ding{83}', u'\u2733'),
    ('\\tone{44}', u'\u02e6'),
    ('\\Epsilon ', u'\u0395'),
    ('\\dotplus ', u'\u2214'),
    ('\\ding{82}', u'\u2732'),
    ('\\epsilon ', u'\u03b5'),
    ('\\Elzglst ', u'\u0294'),
    ('\\ding{61}', u'\u271d'),
    ('\\ding{93}', u'\u273d'),
    ('\\Elzrais ', u'\u02d4'),
    ('\\ding{60}', u'\u271c'),
    ('\\ding{92}', u'\u273c'),
    ('\\ding{39}', u'\u2707'),
    ('\\ding{71}', u'\u2727'),
    ('\\because ', u'\u2235'),
    ('\\boxplus ', u'\u229e'),
    ('\\ding{38}', u'\u2706'),
    ('\\ding{70}', u'\u2726'),
    ('\\partial ', u'\ud74f'),
    ('\\partial ', u'\ud6db'),
    ('\\Elzrtlt ', u'\u0288'),
    ('\\ding{42}', u'\u261b'),
    ('\\not\\leq ', u'\u2270'),
    ('\\ding{81}', u'\u2731'),
    ('\\tone{22}', u'\u02e8'),
    ('\\Elzrtln ', u'\u0273'),
    ('\\ding{73}', u'\u2606'),
    ('\\ding{80}', u'\u2730'),
    ('\\neptune ', u'\u2646'),
    ('\\Elzsqfl ', u'\u25e7'),
    ('\\tone{11}', u'\u02e9'),
    ('\\ding{59}', u'\u271b'),
    ('\\ding{91}', u'\u273b'),
    ('\\textyen', u'\xa5'),
    ('\\textdiv', u'\xf7'),
    ('\\CYRTSHE', u'\u040b'),
    ('\\CYRDZHE', u'\u040f'),
    ('\\CYRSHCH', u'\u0429'),
    ('\\CYREREV', u'\u042d'),
    ('\\cyrshch', u'\u0449'),
    ('\\cyrerev', u'\u044d'),
    ('\\cyrtshe', u'\u045b'),
    ('\\cyrdzhe', u'\u045f'),
    ('\\CYRBYUS', u'\u046a'),
    ('\\cyrbyus', u'\u046b'),
    ('\\CYRFITA', u'\u0472'),
    ('\\cyrfita', u'\u0473'),
    ('\\CYRZDSC', u'\u0498'),
    ('\\cyrzdsc', u'\u0499'),
    ('\\CYRKDSC', u'\u049a'),
    ('\\cyrkdsc', u'\u049b'),
    ('\\CYRNDSC', u'\u04a2'),
    ('\\cyrndsc', u'\u04a3'),
    ('\\CYRSDSC', u'\u04aa'),
    ('\\cyrsdsc', u'\u04ab'),
    ('\\CYRTDSC', u'\u04ac'),
    ('\\cyrtdsc', u'\u04ad'),
    ('\\CYRHDSC', u'\u04b2'),
    ('\\cyrhdsc', u'\u04b3'),
    ('\\CYRSHHA', u'\u04ba'),
    ('\\cyrshha', u'\u04bb'),
    ('\\U\\CYRZH', u'\u04c1'),
    ('\\U\\cyrzh', u'\u04c2'),
    ('\\CYRLDSC', u'\u04c5'),
    ('\\cyrldsc', u'\u04c6'),
    ('\\CYRMDSC', u'\u04cd'),
    ('\\cyrmdsc', u'\u04ce'),
    ('\\"\\CYRZH', u'\u04dc'),
    ('\\"\\cyrzh', u'\u04dd'),
    ('\\CYROTLD', u'\u04e8'),
    ('\\cyrotld', u'\u04e9'),
    ('\\"\\CYRCH', u'\u04f4'),
    ('\\"\\cyrch', u'\u04f5'),
    ('\\CYRGDSC', u'\u04f6'),
    ('\\cyrgdsc', u'\u04f7'),
    ('\\textwon', u'\u20a9'),
    ('\\textohm', u'\u2126'),
    ('\\textmho', u'\u2127'),
    ('\\not\\ni ', u'\u220c'),
    ('\\otimes ', u'\u2297'),
    ('\\saturn ', u'\u2644'),
    ('\\gtrdot ', u'\u22d7'),
    ('\\ElzInf ', u'\u2a07'),
    ('\\nvdash ', u'\u22ac'),
    ('\\circeq ', u'\u2257'),
    ('\\Subset ', u'\u22d0'),
    ('\\nvDash ', u'\u22ad'),
    ('\\not&gt;', u'\u226f'),
    ('\\bigcap ', u'\u22c2'),
    ('\\uranus ', u'\u2645'),
    ('\\forall ', u'\u2200'),
    ('\\Elzbar ', u'\u0336'),
    ('\\succeq ', u'\u2ab0'),
    ('\\boxdot ', u'\u22a1'),
    ('\\eqcirc ', u'\u2256'),
    ('\\supset ', u'\u2283'),
    ('\\square ', u'\u25a1'),
    ('\\nVDash ', u'\u22af'),
    ('\\bumpeq ', u'\u224f'),
    ('\\Stigma ', u'\u03da'),
    ('\\rfloor ', u'\u230b'),
    ('\\ominus ', u'\u2296'),
    ('\\Elzesh ', u'\u0283'),
    ('\\ElzSup ', u'\u2a08'),
    ('\\bigcup ', u'\u22c3'),
    ('\\exists ', u'\u2203'),
    ('\\oslash ', u'\u2298'),
    ('\\cancer ', u'\u264b'),
    ('\\ElzLap ', u'\u29ca'),
    ('\\ElzAnd ', u'\u2a53'),
    ('\\Bumpeq ', u'\u224e'),
    ('\\not&lt;', u'\u226e'),
    ('\\bullet ', u'\u2219'),
    ('\\nVdash ', u'\u22ae'),
    ('\\mapsto ', u'\u21a6'),
    ('\\bowtie ', u'\u22c8'),
    ('\\lfloor ', u'\u230a'),
    ('\\lbrace ', u'{'),
    ('\\rangle ', u'\u232a'),
    ('\\subset ', u'\u2282'),
    ('\\gemini ', u'\u264a'),
    ('\\propto ', u'\u221d'),
    ('\\coprod ', u'\u2210'),
    ('\\varrho ', u'\u03f1'),
    ('\\varphi ', u'\u03c6'),
    ('\\pisces ', u'\u2653'),
    ('\\sqrint ', u'\u2a16'),
    ('\\Lambda ', u'\u039b'),
    ('\\lambda ', u'\u03bb'),
    ('\\taurus ', u'\u2649'),
    ('\\rbrace ', u'}'),
    ('\\preceq ', u'\u2aaf'),
    ('\\diagup ', u'\u2571'),
    ('\\ddddot ', u'\u20dc'),
    ('\\Elzlow ', u'\u02d5'),
    ('\\hslash ', u'\u210f'),
    ('\\veebar ', u'\u22bb'),
    ('\\ElzThr ', u'\u2a05'),
    ('\\Vvdash ', u'\u22aa'),
    ('\\rtimes ', u'\u22ca'),
    ('\\approx ', u'\u2248'),
    ('\\langle ', u'\u2329'),
    ('\\Supset ', u'\u22d1'),
    ('\\ltimes ', u'\u22c9'),
    ('\\daleth ', u'\u2138'),
    ('\\Elzfhr ', u'\u027e'),
    ('\\not\\in ', u'\u2209'),
    ('\\textpm', u'\xb1'),
    ('\\textmu', u'\xb5'),
    ('\\`\\CYRE', u'\u0400'),
    ('\\CYRDJE', u'\u0402'),
    ('\\`\\CYRG', u'\u0403'),
    ('\\CYRDZE', u'\u0405'),
    ('\\CYRLJE', u'\u0409'),
    ('\\CYRNJE', u'\u040a'),
    ('\\`\\CYRK', u'\u040c'),
    ('\\`\\CYRI', u'\u040d'),
    ('\\CYRERY', u'\u042b'),
    ('\\cyrery', u'\u044b'),
    ('\\`\\cyre', u'\u0450'),
    ('\\cyrdje', u'\u0452'),
    ('\\`\\cyrg', u'\u0453'),
    ('\\cyrdze', u'\u0455'),
    ('\\cyrlje', u'\u0459'),
    ('\\cyrnje', u'\u045a'),
    ('\\`\\cyrk', u'\u045c'),
    ('\\`\\cyri', u'\u045d'),
    ('\\CYRYAT', u'\u0462'),
    ('\\cyryat', u'\u0463'),
    ('\\CYRIZH', u'\u0474'),
    ('\\cyrizh', u'\u0475'),
    ('\\CYRGUP', u'\u0490'),
    ('\\cyrgup', u'\u0491'),
    ('\\CYRGHK', u'\u0494'),
    ('\\cyrghk', u'\u0495'),
    ('\\CYRPHK', u'\u04a6'),
    ('\\cyrphk', u'\u04a7'),
    ('\\CYRKHK', u'\u04c3'),
    ('\\cyrkhk', u'\u04c4'),
    ('\\CYRNHK', u'\u04c7'),
    ('\\cyrnhk', u'\u04c8'),
    ('\\U\\CYRA', u'\u04d0'),
    ('\\U\\cyra', u'\u04d1'),
    ('\\"\\CYRA', u'\u04d2'),
    ('\\"\\cyra', u'\u04d3'),
    ('\\U\\CYRE', u'\u04d6'),
    ('\\U\\cyre', u'\u04d7'),
    ('\\"\\CYRZ', u'\u04de'),
    ('\\"\\cyrz', u'\u04df'),
    ('\\=\\CYRI', u'\u04e2'),
    ('\\=\\cyri', u'\u04e3'),
    ('\\"\\CYRI', u'\u04e4'),
    ('\\"\\cyri', u'\u04e5'),
    ('\\"\\CYRO', u'\u04e6'),
    ('\\"\\cyro', u'\u04e7'),
    ('\\=\\CYRU', u'\u04ee'),
    ('\\=\\cyru', u'\u04ef'),
    ('\\"\\CYRU', u'\u04f0'),
    ('\\"\\cyru', u'\u04f1'),
    ('\\H\\CYRU', u'\u04f2'),
    ('\\H\\cyru', u'\u04f3'),
    ('\\CYRHHK', u'\u04fc'),
    ('\\cyrhhk', u'\u04fd'),
    ('\\textpm', u'\xb1'),
    ('\\space ', u' '),
    ('\\Elzrh ', u'\u0322'),
    ('\\image ', u'\u22b7'),
    ('{_\\ast}', u'\u2217'),
    ('\\Colon ', u'\u2237'),
    ('\\frown ', u'\u2322'),
    ('\\Omega ', u'\u2126'),
    ('\\sharp ', u'\u266f'),
    ('\\vdash ', u'\u22a2'),
    ('\\asymp ', u'\u224d'),
    ('\\dddot ', u'\u20db'),
    ('\\angle ', u'\u2220'),
    ('\\VDash ', u'\u22ab'),
    ('\\varpi ', u'\u03d6'),
    ('\\libra ', u'\u264e'),
    ('\\Angle ', u'\u299c'),
    ('\\equiv ', u'\u2261'),
    ('\\Sampi ', u'\u03e0'),
    ('\\ElzOr ', u'\u2a54'),
    ('\\cdots ', u'\u22ef'),
    ('\\Kappa ', u'\u039a'),
    ('\\kappa ', u'\u03ba'),
    ('\\amalg ', u'\u2a3f'),
    ('\\virgo ', u'\u264d'),
    ('\\Equal ', u'\u2a75'),
    ('\\dashv ', u'\u22a3'),
    ('\\venus ', u'\u2640'),
    ('\\gimel ', u'\u2137'),
    ('\\simeq ', u'\u2243'),
    ('\\ldots ', u'\u2026'),
    ('\\Sigma ', u'\u03a3'),
    ('\\sigma ', u'\u03c3'),
    ('\\lnsim ', u'\u22e6'),
    ('\\Theta ', u'\u0398'),
    ('\\smile ', u'\u2323'),
    ('\\vdots ', u'\u22ee'),
    ('\\aleph ', u'\u2135'),
    ('\\Elzrl ', u'\u027c'),
    ('\\nabla ', u'\u2207'),
    ('\\wedge ', u'\u2227'),
    ('\\Alpha ', u'\u0391'),
    ('\\alpha ', u'\u03b1'),
    ('\\aries ', u'\u2648'),
    ('\\sqcup ', u'\u2294'),
    ('\\Elzxh ', u'\u0127'),
    ("\\'{}{I}", u'\u038a'),
    ('\\Elzxl ', u'\u0335'),
    ('\\gnsim ', u'\u22e7'),
    ('\\pluto ', u'\u2647'),
    ('\\uplus ', u'\u228e'),
    ('\\Delta ', u'\u0394'),
    ('\\delta ', u'\u03b4'),
    ('\\doteq ', u'\u2250'),
    ('\\sqcap ', u'\u2293'),
    ('\\Omega ', u'\u03a9'),
    ('\\omega ', u'\u03c9'),
    ('\\lneqq ', u'\u2268'),
    ('\\oplus ', u'\u2295'),
    ('\\rceil ', u'\u2309'),
    ('\\Koppa ', u'\u03de'),
    ('\\lceil ', u'\u2308'),
    ('\\Gamma ', u'\u0393'),
    ('\\infty ', u'\u221e'),
    ('\\Vdash ', u'\u22a9'),
    ('\\gamma ', u'\u03b3'),
    ('\\gneqq ', u'\u2269'),
    ('\\CYRYO', u'\u0401'),
    ('\\CYRIE', u'\u0404'),
    ('\\CYRII', u'\u0406'),
    ('\\CYRYI', u'\u0407'),
    ('\\CYRJE', u'\u0408'),
    ('\\CYRZH', u'\u0416'),
    ('\\CYRCH', u'\u0427'),
    ('\\CYRSH', u'\u0428'),
    ('\\CYRYU', u'\u042e'),
    ('\\CYRYA', u'\u042f'),
    ('\\cyrzh', u'\u0436'),
    ('\\cyrch', u'\u0447'),
    ('\\cyrsh', u'\u0448'),
    ('\\cyryu', u'\u044e'),
    ('\\cyrya', u'\u044f'),
    ('\\cyryo', u'\u0451'),
    ('\\cyrie', u'\u0454'),
    ('\\cyrii', u'\u0456'),
    ('\\cyryi', u'\u0457'),
    ('\\cyrje', u'\u0458'),
    ('\\CYRNG', u'\u04a4'),
    ('\\cyrng', u'\u04a5'),
    ('\\CYRAE', u'\u04d4'),
    ('\\cyrae', u'\u04d5'),
    ('$\\neq$', u'\u2260'),
    ('$\\deg$', u'\xb0'),
    ('\\lneq ', u'\u2a87'),
    ('\\prec ', u'\u227a'),
    ('\\Vert ', u'\u2016'),
    ('\\beth ', u'\u2136'),
    ('\\={\\i}', u'\u012b'),
    ('\\succ ', u'\u227b'),
    ('\\cdot ', u'\xb7'),
    ('\\not =', u'\u2260'),
    ('\\Zeta ', u'\u0396'),
    ('\\u{\\i}', u'\u012d'),
    ('\\lnot ', u'\xac'),
    ('\\zeta ', u'\u03b6'),
    ('\\`{\\i}', u'\xec'),
    ("\\'{\\i}", u'\xed'),
    ('\\nmid ', u'\u2224'),
    ('\\prod ', u'\u220f'),
    ('\\surd ', u'\u221a'),
    ('\\perp ', u'\u22a5'),
    ('\\male ', u'\u2642'),
    ('\\cdot ', u'\u22c5'),
    ('\\cong ', u'\u2245'),
    ('\\flat ', u'\u266d'),
    ('\\^{\\i}', u'\xee'),
    ('\\Iota ', u'\u0399'),
    ('\\circ ', u'\u2218'),
    ('\\iota ', u'\u03b9'),
    ('\\"{\\i}', u'\xef'),
    ('\\gneq ', u'\u2a88'),
    ('\\odot ', u'\u2299'),
    ('\\oint ', u'\u222e'),
    ('\\Beta ', u'\u0392'),
    ('\\beta ', u'\u03b2'),
    ('\\geqq ', u'\u2267'),
    ('\\&amp;', u'&'),
    ('\\vert ', u'|'),
    ('\\ElOr ', u'\u2a56'),
    ('\\leqq ', u'\u2266'),
    ('\\star ', u'\u22c6'),
    ('\\~{\\i}', u'\u0129'),
    ('\\^{\\j}', u'\u0135'),
    ('\\CYRA', u'\u0410'),
    ('\\CYRB', u'\u0411'),
    ('\\CYRV', u'\u0412'),
    ('\\CYRG', u'\u0413'),
    ('\\CYRD', u'\u0414'),
    ('\\CYRE', u'\u0415'),
    ('\\CYRZ', u'\u0417'),
    ('\\CYRI', u'\u0418'),
    ('\\CYRK', u'\u041a'),
    ('\\CYRL', u'\u041b'),
    ('\\CYRM', u'\u041c'),
    ('\\CYRN', u'\u041d'),
    ('\\CYRO', u'\u041e'),
    ('\\CYRP', u'\u041f'),
    ('\\CYRR', u'\u0420'),
    ('\\CYRS', u'\u0421'),
    ('\\CYRT', u'\u0422'),
    ('\\CYRU', u'\u0423'),
    ('\\CYRF', u'\u0424'),
    ('\\CYRH', u'\u0425'),
    ('\\CYRC', u'\u0426'),
    ('\\cyra', u'\u0430'),
    ('\\cyrb', u'\u0431'),
    ('\\cyrv', u'\u0432'),
    ('\\cyrg', u'\u0433'),
    ('\\cyrd', u'\u0434'),
    ('\\cyre', u'\u0435'),
    ('\\cyrz', u'\u0437'),
    ('\\cyri', u'\u0438'),
    ('\\cyrk', u'\u043a'),
    ('\\cyrl', u'\u043b'),
    ('\\cyrm', u'\u043c'),
    ('\\cyrn', u'\u043d'),
    ('\\cyro', u'\u043e'),
    ('\\cyrp', u'\u043f'),
    ('\\cyrr', u'\u0440'),
    ('\\cyrs', u'\u0441'),
    ('\\cyrt', u'\u0442'),
    ('\\cyru', u'\u0443'),
    ('\\cyrf', u'\u0444'),
    ('\\cyrh', u'\u0445'),
    ('\\cyrc', u'\u0446'),
    ('\\CYRY', u'\u04ae'),
    ('\\cyry', u'\u04af'),
    ('\\c{c}', u'\xe7'),
    ('\\c{C}', u'\xc7'),
    ('{\\oe}', u'\u0153'),
    ('{\\OE}', u'\u0152'),
    ('{\\ae}', u'\xe6'),
    ('{\\AE}', u'\xc6'),
    ('{\\aa}', u'\xe5'),
    ('{\\AA}', u'\xc5'),
    ('{\\ss}', u'\xdf'),
    ('\\~{} ', u'~'),
    ('\\^{} ', u'^'),
    ('$\\ge$', u'\u2265'),
    ('$\\le$', u'\u2264'),
    ('$\\mu$', u'\xb5'),
    ('\\.{E}', u'\u0116'),
    ('\\c{K}', u'\u0136'),
    ('\\"{E}', u'\xcb'),
    ('\\c{R}', u'\u0156'),
    ('\\"{e}', u'\xeb'),
    ('\\^{Y}', u'\u0176'),
    ('\\={a}', u'\u0101'),
    ('\\.{g}', u'\u0121'),
    ('\\`{A}', u'\xc0'),
    ('\\v{s}', u'\u0161'),
    ('\\`{a}', u'\xe0'),
    ('\\={A}', u'\u0100'),
    ('\\Eta ', u'\u0397'),
    ('\\.{G}', u'\u0120'),
    ('\\eta ', u'\u03b7'),
    ("\\'{A}", u'\xc1'),
    ("\\'{a}", u'\xe1'),
    ('\\v{S}', u'\u0160'),
    ('\\.{c}', u'\u010b'),
    ("\\'{}O", u'\u038c'),
    ("\\'{o}", u'\u03cc'),
    ('\\"{O}', u'\xd6'),
    ('\\={u}', u'\u016b'),
    ('\\"{o}', u'\xf6'),
    ('\\u{A}', u'\u0102'),
    ('\\Rho ', u'\u03a1'),
    ('\\c{G}', u'\u0122'),
    ('\\rho ', u'\u03c1'),
    ('\\c{T}', u'\u0162'),
    ('\\div ', u'\xf7'),
    ('\\v{c}', u'\u010d'),
    ('\\int ', u'\u222b'),
    ('\\={o}', u'\u014d'),
    ('\\`{I}', u'\xcc'),
    ('\\u{u}', u'\u016d'),
    ('\\v{C}', u'\u010c'),
    ('\\u{I}', u'\u012c'),
    ("\\'{I}", u'\xcd'),
    ('\\={O}', u'\u014c'),
    ('\\geq ', u'\u2265'),
    ('\\u{U}', u'\u016c'),
    ('\\.{e}', u'\u0117'),
    ('\\c{k}', u'\u0137'),
    ('\\^{A}', u'\xc2'),
    ('\\c{r}', u'\u0157'),
    ('\\^{a}', u'\xe2'),
    ('\\^{y}', u'\u0177'),
    ('\\v{D}', u'\u010e'),
    ('\\k{I}', u'\u012e'),
    ('\\~{A}', u'\xc3'),
    ('\\leo ', u'\u264c'),
    ('\\u{O}', u'\u014e'),
    ('\\~{a}', u'\xe3'),
    ('\\r{U}', u'\u016e'),
    ('\\k{e}', u'\u0119'),
    ("\\'{L}", u'\u0139'),
    ('\\v{r}', u'\u0159'),
    ("\\'{Z}", u'\u0179'),
    ('\\k{E}', u'\u0118'),
    ('\\`{U}', u'\xd9'),
    ('\\v{R}', u'\u0158'),
    ('\\`{u}', u'\xf9'),
    ('\\"{Y}', u'\u0178'),
    ('\\u{a}', u'\u0103'),
    ('\\c{g}', u'\u0123'),
    ('\\Tau ', u'\u03a4'),
    ("\\'{N}", u'\u0143'),
    ('\\tau ', u'\u03c4'),
    ('\\^{I}', u'\xce'),
    ('\\c{t}', u'\u0163'),
    ('\\mho ', u'\u2127'),
    ('\\Cup ', u'\u22d3'),
    ('\\v{E}', u'\u011a'),
    ("\\'{l}", u'\u013a'),
    ('\\"{I}', u'\xcf'),
    ("\\'{S}", u'\u015a'),
    ("\\'{z}", u'\u017a'),
    ('\\k{a}', u'\u0105'),
    ('\\mid ', u'\u2223'),
    ('\\^{h}', u'\u0125'),
    ('\\c{N}', u'\u0145'),
    ('\\"{A}', u'\xc4'),
    ('\\v{t}', u'\u0165'),
    ('\\"{a}', u'\xe4'),
    ('\\k{A}', u'\u0104'),
    ('\\^{H}', u'\u0124'),
    ("\\'{n}", u'\u0144'),
    ('\\v{T}', u'\u0164'),
    ('\\v{d}', u'\u010f'),
    ('\\k{i}', u'\u012f'),
    ('\\u{o}', u'\u014f'),
    ("\\'{U}", u'\xda'),
    ('\\r{u}', u'\u016f'),
    ("\\'{u}", u'\xfa'),
    ("\\'{C}", u'\u0106'),
    ('\\Rsh ', u'\u21b1'),
    ('\\sim ', u'\u223c'),
    ('\\c{n}', u'\u0146'),
    ('\\^{U}', u'\xdb'),
    ('\\^{u}', u'\xfb'),
    ('\\H{o}', u'\u0151'),
    ('\\H{u}', u'\u0171'),
    ('\\Chi ', u'\u03a7'),
    ('\\.{I}', u'\u0130'),
    ('\\chi ', u'\u03c7'),
    ('\\~{N}', u'\xd1'),
    ('\\H{O}', u'\u0150'),
    ('\\~{n}', u'\xf1'),
    ('\\H{U}', u'\u0170'),
    ('\\v{e}', u'\u011b'),
    ('\\Lsh ', u'\u21b0'),
    ('\\c{L}', u'\u013b'),
    ("\\'{s}", u'\u015b'),
    ('\\.{Z}', u'\u017b'),
    ('\\={E}', u'\u0112'),
    ('\\c{C}', u'\xc7'),
    ('\\leq ', u'\u2264'),
    ('\\c{c}', u'\xe7'),
    ('\\k{U}', u'\u0172'),
    ("\\'{A}", u'\u0386'),
    ('\\^{g}', u'\u011d'),
    ('\\Phi ', u'\u03a6'),
    ('\\v{L}', u'\u013d'),
    ('\\^{s}', u'\u015d'),
    ('\\"{U}', u'\xdc'),
    ('\\Cap ', u'\u22d2'),
    ('\\v{Z}', u'\u017d'),
    ('\\"{u}', u'\xfc'),
    ('\\^{G}', u'\u011c'),
    ('\\c{l}', u'\u013c'),
    ("\\'{Y}", u'\xdd'),
    ('\\^{S}', u'\u015c'),
    ("\\'{y}", u'\xfd'),
    ('\\.{z}', u'\u017c'),
    ("\\'{c}", u'\u0107'),
    ('\\sum ', u'\u2211'),
    ('\\v{N}', u'\u0147'),
    ('\\`{O}', u'\xd2'),
    ('\\top ', u'\u22a4'),
    ('\\`{o}', u'\xf2'),
    ('\\u{G}', u'\u011e'),
    ('\\v{l}', u'\u013e'),
    ("\\'{O}", u'\xd3'),
    ('\\phi ', u'\u03d5'),
    ('\\c{S}', u'\u015e'),
    ("\\'{o}", u'\xf3'),
    ('\\v{z}', u'\u017e'),
    ('\\^{c}', u'\u0109'),
    ('\\`{E}', u'\xc8'),
    ('\\~{u}', u'\u0169'),
    ('\\`{e}', u'\xe8'),
    ('\\^{C}', u'\u0108'),
    ('\\~{I}', u'\u0128'),
    ('\\cup ', u'\u222a'),
    ("\\'{E}", u'\xc9'),
    ('\\v{n}', u'\u0148'),
    ("\\'{e}", u'\xe9'),
    ('\\~{U}', u'\u0168'),
    ('\\={e}', u'\u0113'),
    ('\\k{u}', u'\u0173'),
    ("\\'{H}", u'\u0389'),
    ('\\.{C}', u'\u010a'),
    ('\\vee ', u'\u2228'),
    ('\\={I}', u'\u012a'),
    ("{'''}", u'\u2034'),
    ('\\={U}', u'\u016a'),
    ("\\'{g}", u'\u01f5'),
    ('\\"{y}', u'\xff'),
    ('\\u{e}', u'\u0115'),
    ('\\eth ', u'\u01aa'),
    ("\\'{r}", u'\u0155'),
    ('\\^{O}', u'\xd4'),
    ('\\^{w}', u'\u0175'),
    ('\\^{o}', u'\xf4'),
    ('\\u{E}', u'\u0114'),
    ('\\ast ', u'*'),
    ('\\^{J}', u'\u0134'),
    ('\\~{O}', u'\xd5'),
    ("\\'{R}", u'\u0154'),
    ('\\~{o}', u'\xf5'),
    ('\\^{W}', u'\u0174'),
    ("\\'{E}", u'\u0388'),
    ('\\u{g}', u'\u011f'),
    ('\\cap ', u'\u2229'),
    ('\\Psi ', u'\u03a8'),
    ('\\psi ', u'\u03c8'),
    ('\\^{E}', u'\xca'),
    ('\\c{s}', u'\u015f'),
    ('\\^{e}', u'\xea'),
    ('\\c\\ ', u'\xb8'),
    ('\\r A', u'\xc5'),
    ('\\c C', u'\xc7'),
    ('\\r a', u'\xe5'),
    ('\\c c', u'\xe7'),
    ('\\`\\i', u'\xec'),
    ("\\'\\i", u'\xed'),
    ('\\^\\i', u'\xee'),
    ('\\"\\i', u'\xef'),
    ('\\u A', u'\u0102'),
    ('\\u a', u'\u0103'),
    ('\\k A', u'\u0104'),
    ('\\k a', u'\u0105'),
    ('\\v C', u'\u010c'),
    ('\\v c', u'\u010d'),
    ('\\v D', u'\u010e'),
    ('\\v d', u'\u010f'),
    ('\\k E', u'\u0118'),
    ('\\k e', u'\u0119'),
    ('\\v E', u'\u011a'),
    ('\\v e', u'\u011b'),
    ('\\u G', u'\u011e'),
    ('\\u g', u'\u011f'),
    ('\\v L', u'\u013d'),
    ('\\v l', u'\u013e'),
    ('\\v N', u'\u0147'),
    ('\\v n', u'\u0148'),
    ('\\H O', u'\u0150'),
    ('\\H o', u'\u0151'),
    ('\\v R', u'\u0158'),
    ('\\v r', u'\u0159'),
    ('\\c S', u'\u015e'),
    ('\\c s', u'\u015f'),
    ('\\v S', u'\u0160'),
    ('\\v s', u'\u0161'),
    ('\\c T', u'\u0162'),
    ('\\c t', u'\u0163'),
    ('\\v T', u'\u0164'),
    ('\\v t', u'\u0165'),
    ('\\r U', u'\u016e'),
    ('\\r u', u'\u016f'),
    ('\\H U', u'\u0170'),
    ('\\H u', u'\u0171'),
    ('\\v Z', u'\u017d'),
    ('\\v z', u'\u017e'),
    ('\\`\\i', u'\xec'),
    ('\\`\\I', u'\xcc'),
    ("\\'\\i", u'\xed'),
    ("\\'\\I", u'\xcd'),
    ('\\^\\i', u'\xee'),
    ('\\^\\I', u'\xce'),
    ('\\"\\i', u'\xef'),
    ('\\"\\I', u'\xcf'),
    ('{\\o}', u'\xf8'),
    ('{\\O}', u'\xd8'),
    ('{!`}', u'\xa1'),
    ('{?`}', u'\xbf'),
    ('\\~{}', u'~'),
    ('{\\i}', u'\u0131'),
    ('\\ng ', u'\u014b'),
    ('\\wr ', u'\u2240'),
    ('\\ni ', u'\u220b'),
    ("''''", u'\u2057'),
    ('\\gg ', u'\u226b'),
    ('\\Pi ', u'\u03a0'),
    ('\\pi ', u'\u03c0'),
    ('\\c{}', u'\xb8'),
    ('{^1}', u'\xb9'),
    ('\\r{}', u'\u02da'),
    ('\\AA ', u'\xc5'),
    ('\\aa ', u'\xe5'),
    ('\\nu ', u'\u03bd'),
    ('\\dj ', u'\u0111'),
    ('\\DH ', u'\xd0'),
    ('\\dh ', u'\xf0'),
    ('\\DJ ', u'\u0110'),
    ('\\pm ', u'\xb1'),
    ('\\H{}', u'\u02dd'),
    ('\\mu ', u'\u03bc'),
    ('\\AE ', u'\xc6'),
    ('\\ae ', u'\xe6'),
    ('\\AA ', u'\u212b'),
    ('\\OE ', u'\u0152'),
    ('\\k{}', u'\u02db'),
    ('{^2}', u'\xb2'),
    ('{^3}', u'\xb3'),
    ("{''}", u'\u2033'),
    ('\\^{}', u'^'),
    ('\\ll ', u'\u226a'),
    ('\\oe ', u'\u0153'),
    ('\\TH ', u'\xde'),
    ('\\th ', u'\xfe'),
    ('\\in ', u'\u2208'),
    ('\\NG ', u'\u014a'),
    ('\\ss ', u'\xdf'),
    ('\\mp ', u'\u2213'),
    ('\\wp ', u'\u2118'),
    ('\\Xi ', u'\u039e'),
    ('\\xi ', u'\u03be'),
    ('\\`A', u'\xc0'),
    ("\\'A", u'\xc1'),
    ('\\^A', u'\xc2'),
    ('\\~A', u'\xc3'),
    ('\\"A', u'\xc4'),
    ('\\AE', u'\xc6'),
    ('\\`E', u'\xc8'),
    ("\\'E", u'\xc9'),
    ('\\^E', u'\xca'),
    ('\\"E', u'\xcb'),
    ('\\`I', u'\xcc'),
    ("\\'I", u'\xcd'),
    ('\\^I', u'\xce'),
    ('\\"I', u'\xcf'),
    ('\\DH', u'\xd0'),
    ('\\~N', u'\xd1'),
    ('\\`O', u'\xd2'),
    ("\\'O", u'\xd3'),
    ('\\^O', u'\xd4'),
    ('\\~O', u'\xd5'),
    ('\\"O', u'\xd6'),
    ('\\`U', u'\xd9'),
    ("\\'U", u'\xda'),
    ('\\^U', u'\xdb'),
    ('\\"U', u'\xdc'),
    ("\\'Y", u'\xdd'),
    ('\\TH', u'\xde'),
    ('\\ss', u'\xdf'),
    ('\\`a', u'\xe0'),
    ("\\'a", u'\xe1'),
    ('\\^a', u'\xe2'),
    ('\\~a', u'\xe3'),
    ('\\"a', u'\xe4'),
    ('\\ae', u'\xe6'),
    ('\\`e', u'\xe8'),
    ("\\'e", u'\xe9'),
    ('\\^e', u'\xea'),
    ('\\"e', u'\xeb'),
    ('\\dh', u'\xf0'),
    ('\\~n', u'\xf1'),
    ('\\`o', u'\xf2'),
    ("\\'o", u'\xf3'),
    ('\\^o', u'\xf4'),
    ('\\~o', u'\xf5'),
    ('\\"o', u'\xf6'),
    ('\\`u', u'\xf9'),
    ("\\'u", u'\xfa'),
    ('\\^u', u'\xfb'),
    ('\\"u', u'\xfc'),
    ("\\'y", u'\xfd'),
    ('\\th', u'\xfe'),
    ('\\"y', u'\xff'),
    ("\\'C", u'\u0106'),
    ("\\'c", u'\u0107'),
    ('\\DJ', u'\u0110'),
    ('\\dj', u'\u0111'),
    ('\\.I', u'\u0130'),
    ('\\IJ', u'\u0132'),
    ('\\ij', u'\u0133'),
    ("\\'L", u'\u0139'),
    ("\\'l", u'\u013a'),
    ("\\'N", u'\u0143'),
    ("\\'n", u'\u0144'),
    ('\\NG', u'\u014a'),
    ('\\ng', u'\u014b'),
    ('\\OE', u'\u0152'),
    ('\\oe', u'\u0153'),
    ("\\'R", u'\u0154'),
    ("\\'r", u'\u0155'),
    ("\\'S", u'\u015a'),
    ("\\'s", u'\u015b'),
    ('\\"Y', u'\u0178'),
    ("\\'Z", u'\u0179'),
    ("\\'z", u'\u017a'),
    ('\\.Z', u'\u017b'),
    ('\\.z', u'\u017c'),
    ('\\`a', u'\xe0'),
    ('\\`e', u'\xe8'),
    ('\\`o', u'\xf2'),
    ('\\`u', u'\xf9'),
    ('\\`y', u'\u1ef3'),
    ('\\`A', u'\xc0'),
    ('\\`E', u'\xc8'),
    ('\\`O', u'\xd2'),
    ('\\`U', u'\xd9'),
    ('\\`Y', u'\u1ef2'),
    ("\\'a", u'\xe1'),
    ("\\'e", u'\xe9'),
    ("\\'i", u'\xed'),
    ("\\'o", u'\xf3'),
    ("\\'u", u'\xfa'),
    ("\\'y", u'\xfd'),
    ("\\'A", u'\xc1'),
    ("\\'E", u'\xc9'),
    ("\\'O", u'\xd3'),
    ("\\'U", u'\xda'),
    ("\\'Y", u'\xdd'),
    ('\\^a', u'\xe2'),
    ('\\^e', u'\xea'),
    ('\\^o', u'\xf4'),
    ('\\^u', u'\xfb'),
    ('\\^y', u'\u0177'),
    ('\\^A', u'\xc2'),
    ('\\^E', u'\xca'),
    ('\\^O', u'\xd4'),
    ('\\^U', u'\xdb'),
    ('\\^Y', u'\u0176'),
    ('\\"a', u'\xe4'),
    ('\\"e', u'\xeb'),
    ('\\"o', u'\xf6'),
    ('\\"u', u'\xfc'),
    ('\\"y', u'\xff'),
    ('\\"A', u'\xc4'),
    ('\\"E', u'\xcb'),
    ('\\"O', u'\xd6'),
    ('\\"U', u'\xdc'),
    ('\\"Y', u'\u0178'),
    ('---', u'\u2014'),
    ('\\ss', u'\xdf'),
    ('\\L ', u'\u0141'),
    ('\\in', u'\ud7c4'),
    ('\\l ', u'\u0142'),
    ('\\in', u'\ud78a'),
    ('\\in', u'\ud716'),
    ('\\O ', u'\xd8'),
    ('\\o ', u'\xf8'),
    ('\\i ', u'\u0131'),
    ('\\in', u'\ud750'),
    ("{'}", u'\u2032'),
    ('\\in', u'\ud6dc'),
    ('\\O', u'\xd8'),
    ('\\o', u'\xf8'),
    ('\\i', u'\u0131'),
    ('\\L', u'\u0141'),
    ('\\l', u'\u0142'),
    ('--', u'\u2013'),
    ('\\\\', u'\\'),
    ('\\~', u'~'),
    ('\\&', u'&'),
    ('\\$', u'$'),
    ('\\{', u'{'),
    ('\\}', u'}'),
    ('\\%', u'%'),
    ('\\#', u'#'),
    ('\\_', u'_'),
    ('\\v', u'\u030c'),
    ('\\-', u'\xad'),
    ('\\H', u'\u030b'),
    ('\\#', u'#'),
    ('\\%', u'%'),
    ('\\;', u'\u2009-0200A-0200A'),
    ('\\c', u'\u0327'),
    (':=', u'\u2254'),
    ('\\u', u'\u0306'),
    ('\\r', u'\u030a'),
    ("'n", u'\u0149'),
    (',,', u'\u201e'),
    ('=:', u'\u2255'),
    ('..', u'\u2025'),
    ('\\_', u'_'),
    ('\\k', u'\u0328'))